import type { CharacterVoiceId, VoiceLineKind } from "./testimony-speech.ts";

export type VoiceAssetKey = `${CharacterVoiceId}:${VoiceLineKind}`;

// Generated by scripts/warm-voice-assets.mjs. Do not replace these URLs at runtime.
export const VOICE_ASSET_URLS: Readonly<Partial<Record<VoiceAssetKey, string>>> = Object.freeze({
  "tiantian:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173551_18c53022432578dd6ef1.wav",
  "tiantian:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173604_18c530256f79e000b2ab.wav",
  "qiao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173617_18c5302867c937881e27.wav",
  "qiao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173635_18c5302ca3b8e0a9cf89.wav",
  "xiao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173649_18c5302ff216d4873059.wav",
  "xiao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173701_18c53032aadb514e6783.wav",
  "zhao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173719_18c53036d5973daddc35.wav",
  "zhao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173736_18c5303ad1c64000c44c.wav",
  "han:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173749_18c5303de1120f353898.wav",
  "han:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173800_18c530404ab6c0f213ad.wav",
  "zhang:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173811_18c53042fa7bbbc51342.wav",
  "zhang:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173826_18c530466ed1c2fb3341.wav",
  "li:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173837_18c53048f4064b268fac.wav",
  "li:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173846_18c5304b329b3f97a297.wav",
  "lin:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173859_18c5304e3a70279ac80b.wav",
  "lin:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173912_18c5305148a3a893547a.wav",
  "qixia:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173935_18c53056939e1ba77b7f.wav",
  "qixia:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724173952_18c5305a9616215a54d5.wav"
});

export function voiceAssetFor(characterId: CharacterVoiceId, kind: VoiceLineKind) {
  return VOICE_ASSET_URLS[`${characterId}:${kind}`];
}
