import type { CharacterVoiceId, VoiceLineKind } from "./testimony-speech.ts";

export type VoiceAssetKey = `${CharacterVoiceId}:${VoiceLineKind}`;
export const VOICE_ASSET_MODEL = "doubao-tts-2.0";

// Generated by scripts/warm-voice-assets.mjs. Do not replace these URLs at runtime.
export const VOICE_ASSET_URLS: Readonly<Partial<Record<VoiceAssetKey, string>>> = Object.freeze({
  "tiantian:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175519_18c53132528d14ea067e.mp3",
  "tiantian:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175532_18c531354d78ea356e9b.mp3",
  "qiao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175542_18c53137c823c1e6c2c9.mp3",
  "qiao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175552_18c5313a0d8f9469ddcf.mp3",
  "xiao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175609_18c5313de461781e240c.mp3",
  "xiao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175619_18c5314042ef4fbd4d83.mp3",
  "zhao:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175631_18c531430a749f072f5e.mp3",
  "zhao:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175651_18c53147d80e3552616d.mp3",
  "han:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175703_18c5314a788865ec063c.mp3",
  "han:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175715_18c5314d5a5ef49d2f26.mp3",
  "zhang:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175726_18c5314ffb9d92eb1216.mp3",
  "zhang:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175738_18c53152a5c475288803.mp3",
  "li:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175748_18c53154fa2b45ec903d.mp3",
  "li:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175759_18c531577fe447f3b1fc.mp3",
  "lin:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175809_18c53159e1c15a597551.mp3",
  "lin:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175820_18c5315c6e2f7d99b6b5.mp3",
  "qixia:testimony": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175831_18c5315f0169c8fb6c48.mp3",
  "qixia:followUp": "https://cos.lingkeai.vip/uploads/2026.07/24/20260724175843_18c53161b6942ade9e1c.mp3"
});

// Every follow-up is rendered with Qi Xia's fixed male voice, not the witness voice.
export const VOICE_ASSET_SPEAKERS: Readonly<Partial<Record<VoiceAssetKey, CharacterVoiceId>>> = Object.freeze({
  "tiantian:testimony": "tiantian",
  "tiantian:followUp": "qixia",
  "qiao:testimony": "qiao",
  "qiao:followUp": "qixia",
  "xiao:testimony": "xiao",
  "xiao:followUp": "qixia",
  "zhao:testimony": "zhao",
  "zhao:followUp": "qixia",
  "han:testimony": "han",
  "han:followUp": "qixia",
  "zhang:testimony": "zhang",
  "zhang:followUp": "qixia",
  "li:testimony": "li",
  "li:followUp": "qixia",
  "lin:testimony": "lin",
  "lin:followUp": "qixia",
  "qixia:testimony": "qixia",
  "qixia:followUp": "qixia"
});

export function voiceAssetFor(characterId: CharacterVoiceId, kind: VoiceLineKind) {
  return VOICE_ASSET_URLS[`${characterId}:${kind}`];
}
