import type { StoryChapterSpec, StorySourceRef } from "./types.ts";

const summary = (chapterStart: number, chapterEnd: number, lineStart: number, lineEnd: number): StorySourceRef => ({
  chapterStart,
  chapterEnd,
  lineStart,
  lineEnd,
  kind: "summary",
});

const quote = (chapter: number, line: number): StorySourceRef => ({
  chapterStart: chapter,
  chapterEnd: chapter,
  lineStart: line,
  lineEnd: line,
  kind: "quote",
});

const adaptation = (chapter: number, lineStart: number, lineEnd = lineStart): StorySourceRef => ({
  chapterStart: chapter,
  chapterEnd: chapter,
  lineStart,
  lineEnd,
  kind: "adaptation",
});

export const chapterSix: StoryChapterSpec = {
  id: 6,
  slug: "gokudo",
  title: "极道",
  subtitle: "不同年代、钟响陷阱与被焚毁的九十六颗道",
  source: { startLine: 6745, endLine: 8060, chapters: [49, 50, 51, 52, 53, 54, 55, 56, 57] },
  initialDaoLedger: { qixiaParty: 96, liZhang: 1, oldLu: 0, burned: 0 },
  pressureLimit: 12,
  completionTitle: "极道留下两具尸体",
  completionText: "乔家劲与甜甜固定死亡，九十六颗“道”全部被焚毁。齐夏与林檎没有可支配的“道”，只能去找带走起始一颗的李尚武；此刻还不知道他与章晨泽赛后的余额。",
  completionDaoLedger: { qixiaParty: 0, liZhang: 1, oldLu: 0, burned: 96 },
  completionDaoLabel: "已确认账：齐夏队0；李/章起始筹码1（赛果未核）；焚毁96",
  nextChapterId: 7,
  scenes: [
    {
      id: "c6-share-ledger",
      title: "九十六颗",
      eyebrow: "第二天 / 废弃餐厅",
      lead: "四只布袋重新放到桌上。先把地牛游戏的收益、赛前余数和四人分账核清；这个数字稍后会决定整章的损失。",
      sourceRef: summary(49, 49, 6745, 6898),
      backgroundAsset: "/art/chapter-06/abandoned-restaurant-v1.png",
      portraitIds: ["qixia", "qiao", "tiantian", "lin"],
      observations: [
        { id: "c6-five-shares", label: "五人份收益", text: "四名队员各自通关，齐夏又按交易取得小眼镜和老吕的一份净奖励，合计九十五颗。", note: "九十五不能被四整除。", sourceRef: summary(49, 49, 6747, 6753) },
        { id: "c6-old-one", label: "赛前余数", text: "进入地牛游戏后，齐夏的队伍还剩一颗未投入的“道”。", note: "这颗与九十五颗放到同一账户后再分。", sourceRef: summary(49, 49, 6751, 6757) },
      ],
      dialogue: [
        { id: "c06-qixia-001", speakerId: "qixia", text: "我可是骗子。", sourceRef: quote(49, 6759) },
        { id: "c06-qiao-001", speakerId: "qiao", text: "接下来去哪？", sourceRef: quote(49, 6763) },
      ],
      puzzle: {
        id: "c6-ledger-board",
        prompt: "先把总数和每人份额同时闭合。",
        requiredObservationIds: ["c6-five-shares", "c6-old-one"],
        errorCost: 1,
        solvedText: "九十五加一等于九十六；四人各二十四颗。四只布袋共同属于齐夏行动队账户。",
        fields: [
          { id: "total", label: "可分总数", correctValue: "96", options: [{ value: "95", label: "95" }, { value: "96", label: "96" }, { value: "114", label: "114" }], wrongMessages: { "95": "九十五是地牛局净收益，还漏了赛前剩下的一颗。", "114": "三十八颗交易奖励已经包含在九十五颗内，不能重复相加。" } },
          { id: "per-person", label: "四人各持", correctValue: "24", options: [{ value: "19", label: "19" }, { value: "24", label: "24" }, { value: "25", label: "25" }], wrongMessages: { "19": "十九是单名通关者的地牛奖励，不是最终四人分账。", "25": "九十六除以四是二十四，没有多出的四颗。" } },
        ],
      },
      animationId: "c6-ledger-share",
      advanceLabel: "围着熊肉坐下",
    },
    {
      id: "c6-different-years",
      title: "不在同一年",
      eyebrow: "熊掌煮熟前",
      lead: "“因特网”让饭桌突然安静。四个人说出的“现在”互不相同；只能冻结事实，不能提前解释原因。",
      sourceRef: summary(50, 50, 6899, 7050),
      backgroundAsset: "/art/chapter-06/abandoned-restaurant-v1.png",
      portraitIds: ["qiao", "tiantian", "lin", "qixia"],
      observations: [
        { id: "c6-internet-word", label: "因特网", text: "乔家劲把因特网当作前些年才兴起的新事物；林檎只在历史书里见过这个叫法。", note: "两人的常识不属于同一年代。", sourceRef: summary(50, 50, 6899, 6925) },
        { id: "c6-four-answers", label: "四个回答", text: "乔家劲、甜甜、林檎和齐夏分别直接回答了自己所处的年份。", note: "四个答案互不相同，但都与各自记忆一致。", sourceRef: summary(50, 50, 6923, 6965) },
      ],
      dialogue: [
        { id: "c06-lin-001", speakerId: "lin", text: "各位……我来自2068年……", sourceRef: quote(50, 6935) },
        { id: "c06-qixia-002", speakerId: "qixia", text: "我来自2022年。", sourceRef: quote(50, 6961) },
      ],
      puzzle: {
        id: "c6-year-board",
        prompt: "把四个人的年份按人物固定，再选择此刻唯一能下的结论。",
        requiredObservationIds: ["c6-internet-word", "c6-four-answers"],
        errorCost: 1,
        solvedText: "乔家劲2006、甜甜2019、齐夏2022、林檎2068。此刻只能确认众人来自不同年份。",
        fields: [
          { id: "years", label: "人物与年份", correctValue: "qiao06-tian19-qi22-lin68", options: [{ value: "qiao06-tian19-qi22-lin68", label: "乔2006 / 甜2019 / 齐2022 / 林2068" }, { value: "qiao19-tian06-qi68-lin22", label: "乔2019 / 甜2006 / 齐2068 / 林2022" }, { value: "all-2022", label: "四人都来自2022" }], wrongMessages: { "qiao19-tian06-qi68-lin22": "人物顺序与饭桌上的直接回答不符。", "all-2022": "乔家劲、甜甜和林檎都给出了不同于2022的年份。" } },
          { id: "year-conclusion", label: "当前结论", correctValue: "different-times", options: [{ value: "different-times", label: "来自不同年份" }, { value: "time-travel-solved", label: "已经证明穿越机制" }, { value: "someone-lied", label: "必有一人撒谎" }], wrongMessages: { "time-travel-solved": "年份矛盾只能证明时间来源不同，无法解释机制。", "someone-lied": "所有人的常识和身体状态都支持各自回答，当前没有撒谎证据。" } },
        ],
      },
      animationId: "c6-time-fracture",
      advanceLabel: "继续吃饭",
    },
    {
      id: "c6-bell-trap",
      title: "钟响之后",
      eyebrow: "能力发动",
      lead: "四个人先后失去对身体的控制。不要把饭菜直接定性为毒物：必须把发生顺序、共同触发点和潇潇的动作分开。",
      sourceRef: summary(51, 51, 7051, 7192),
      backgroundAsset: "/art/chapter-06/abandoned-restaurant-v1.png",
      portraitIds: ["xiaoxiao", "qixia", "qiao", "tiantian"],
      observations: [
        { id: "c6-paralysis", label: "失去控制", text: "众人意识清醒，却无法自由控制手脚；齐夏没有确认任何入口、气味或毒性反应。", note: "“吃了肉”与“中毒”不是同一条事实。", sourceRef: summary(51, 51, 7071, 7139) },
        { id: "c6-bell-timing", label: "钟声与布袋", text: "异常发生在钟响后的同一时段；潇潇逐个取下四只布袋并走向炉火。", note: "四只布袋里合计九十六颗。", sourceRef: summary(51, 51, 7139, 7165) },
      ],
      dialogue: [
        { id: "c06-xiaoxiao-001", speakerId: "xiaoxiao", text: "我不允许有人收集成功，我要保护这个地方，若你继续执迷不悟，我会让你后悔的。", sourceRef: quote(51, 7145) },
        { id: "c06-qixia-003", speakerId: "qixia", text: "你到底有什么毛病？！", sourceRef: quote(51, 7163) },
      ],
      puzzle: {
        id: "c6-trap-board",
        prompt: "区分已证事实与仍未证明的因果，再冻结九十六颗的去向。",
        requiredObservationIds: ["c6-paralysis", "c6-bell-timing"],
        errorCost: 2,
        solvedText: "食物中毒没有被证明；钟声与未知能力共同出现在失控节点。潇潇将九十六颗全部投入炉火。",
        fields: [
          { id: "food-cause", label: "饭菜是否投毒", correctValue: "not-proven", options: [{ value: "confirmed-poison", label: "已确认投毒" }, { value: "not-proven", label: "尚未证明" }, { value: "safe-food", label: "已确认绝对安全" }], wrongMessages: { "confirmed-poison": "没有毒物、入口或典型中毒反应证据。", "safe-food": "不能证明投毒，也不能反向证明食物绝对安全。" } },
          { id: "trigger", label: "共同节点", correctValue: "bell-ability", options: [{ value: "bell-ability", label: "钟响与未知能力" }, { value: "bear-meat", label: "熊肉本身" }, { value: "different-years", label: "年份矛盾" }], wrongMessages: { "bear-meat": "熊肉只是时间上更早发生，不能解释意识清醒的统一失控。", "different-years": "年份矛盾与当下身体控制没有直接证据链。" } },
          { id: "dao-fate", label: "九十六颗去向", correctValue: "all-burned", options: [{ value: "all-burned", label: "全部焚毁" }, { value: "xiaoxiao-kept", label: "被潇潇据为己有" }, { value: "one-bag-hidden", label: "暗藏一袋" }], wrongMessages: { "xiaoxiao-kept": "潇潇没有收走作为自己的筹码，而是当面投入炉火。", "one-bag-hidden": "四个人腰间的布袋都被逐一取下，没有隐藏袋证据。" } },
        ],
      },
      animationId: "c6-dao-burn",
      daoLedgerDeltaOnSolve: { qixiaParty: -96, burned: 96 },
      advanceLabel: "看着炉火熄灭",
    },
    {
      id: "c6-gokudo",
      title: "极道万岁",
      eyebrow: "固定正史 / 不可救援",
      lead: "这一幕没有“救谁”的伪分支。你只能确认发生顺序；任何按钮都不能把乔家劲或甜甜从本轮结果中带回来。",
      sourceRef: summary(52, 52, 7193, 7346),
      backgroundAsset: "/art/chapter-06/abandoned-restaurant-v1.png",
      portraitIds: ["xiaoxiao", "qixia", "qiao", "tiantian"],
      observations: [
        { id: "c6-qiao-falls", label: "第一次落板", text: "钉板先落向乔家劲；齐夏随后短暂恢复行动，却仍无法压倒潇潇。", note: "乔家劲先死亡。", sourceRef: summary(52, 52, 7201, 7267) },
        { id: "c6-tiantian-falls", label: "第二次落板", text: "潇潇摆脱齐夏后走向甜甜，再次落下钉板。", note: "甜甜随后死亡，钟声再次传来。", sourceRef: summary(52, 52, 7269, 7285) },
      ],
      dialogue: [
        { id: "c06-qixia-004", speakerId: "qixia", text: "你说话啊乔家劲……你他妈装什么……熊都没打死你……钉子怎么可能杀死你……？", sourceRef: quote(52, 7219) },
        { id: "c06-xiaoxiao-002", speakerId: "xiaoxiao", text: "极道万岁。", sourceRef: quote(52, 7269) },
      ],
      canonicalEvent: "乔家劲先被钉板杀死，甜甜随后死亡。齐夏短暂挣脱未知能力，但没能改变结果。",
      animationId: "c6-gokudo-strike",
      advanceLabel: "记住死亡顺序",
    },
    {
      id: "c6-rule-gap",
      title: "没有杀人夺道",
      eyebrow: "尸体旁的规则复盘",
      lead: "林檎醒来后，四个人的“道”都已消失。齐夏必须按时间顺序复盘潇潇如何避开“杀人夺道”的限制。",
      sourceRef: summary(53, 53, 7347, 7464),
      backgroundAsset: "/art/chapter-06/abandoned-restaurant-v1.png",
      portraitIds: ["qixia", "lin"],
      observations: [
        { id: "c6-no-dao", label: "四个空腰间", text: "齐夏、林檎以及两名死者腰间都没有布袋；熄灭炉火旁留有焚烧痕迹。", note: "没有证据显示潇潇把这四袋“道”据为己有。", sourceRef: summary(53, 53, 7391, 7403) },
        { id: "c6-alive-order", label: "取袋时仍活着", text: "潇潇取下并焚烧布袋时，乔家劲与甜甜还活着；杀人发生在焚毁之后。", note: "三个动作的先后可被独立确认。", sourceRef: summary(53, 53, 7397, 7405) },
      ],
      dialogue: [
        { id: "c06-lin-002", speakerId: "lin", text: "你不是说过，「裁判」不可能允许「杀人夺道」这种事情发生的吗？", sourceRef: quote(53, 7401) },
        { id: "c06-qixia-005", speakerId: "qixia", text: "她没有「夺道」，她只是把「道」摧毁了。", sourceRef: quote(53, 7403) },
        { id: "c06-qixia-006", speakerId: "qixia", text: "我们并不是没有「道」了，还有一颗存放在熟人那里。", sourceRef: quote(53, 7443) },
      ],
      puzzle: {
        id: "c6-rule-gap-board",
        prompt: "选择唯一同时符合动作顺序与规则文字的链条。",
        requiredObservationIds: ["c6-no-dao", "c6-alive-order"],
        errorCost: 1,
        solvedText: "活着时取下布袋 → 焚毁“道” → 最后杀人。她没有在死亡后夺取“道”。",
        fields: [{ id: "sequence", label: "规则链", correctValue: "remove-burn-kill", options: [{ value: "remove-burn-kill", label: "活着取下 → 焚毁 → 杀人" }, { value: "kill-take-keep", label: "杀人 → 夺走 → 自用" }, { value: "kill-burn-take", label: "杀人 → 焚毁 → 取走" }], wrongMessages: { "kill-take-keep": "尸体死亡前布袋已经被取走并投入火中，也没有自用证据。", "kill-burn-take": "焚毁发生在两人死亡之前，且焚毁后无物可取。" } }],
      },
      animationId: "c6-rule-gap",
      advanceLabel: "去找仅剩的一颗",
    },
    {
      id: "c6-return-store",
      title: "便利店没有答案",
      eyebrow: "第二天 / 黄昏前",
      lead: "齐夏与林檎回到便利店。地面没有新鲜血迹或打斗迹象；赵海博与肖冉只能提供李尚武一队的去向。",
      sourceRef: summary(54, 54, 7465, 7612),
      backgroundAsset: "/art/chapter-03/ruined-convenience-store-v1.png",
      portraitIds: ["qixia", "lin", "zhao", "xiao"],
      observations: [
        { id: "c6-store-no-blood", label: "没有新血迹", text: "便利店地面依旧脏乱，但没有新鲜血迹，也没有打斗迹象。", note: "这只记录店内现状，不能替任何人证明全部行踪。", sourceRef: summary(54, 54, 7547, 7551) },
        { id: "c6-li-left", label: "李尚武已经离开", text: "李尚武带走队伍仅剩的一颗“道”去参加对面游戏，和章晨泽随后离开。", note: "这一颗是参赛前的起始筹码，不代表二人离开时的最终余额。", sourceRef: summary(54, 54, 7567, 7597) },
      ],
      dialogue: [],
      puzzle: {
        id: "c6-store-board",
        prompt: "便利店证据只允许确认哪一件事？",
        requiredObservationIds: ["c6-store-no-blood", "c6-li-left"],
        errorCost: 1,
        solvedText: "只能确认李尚武用队伍仅剩的一颗参赛，随后与章晨泽离开；此刻不知道二人赛后的准确余额。赵海博、肖冉是否涉入其他死亡仍无证据。",
        fields: [{ id: "store-conclusion", label: "可确认结论", correctValue: "li-zhang-left", options: [{ value: "li-zhang-left", label: "李与章带起始一颗参赛后离开" }, { value: "zhao-killer", label: "赵海博已经杀人" }, { value: "xiao-killer", label: "肖冉已经杀人" }], wrongMessages: { "zhao-killer": "店内没有新鲜血迹或打斗迹象，也没有赵海博杀人的目击或物证。", "xiao-killer": "肖冉的态度与衣着不是杀人证据；现有口供只说明李、章已经离开。" } }],
      },
      advanceLabel: "制作火把离开",
    },
    {
      id: "c6-insect-reveal",
      title: "窸窸窣窣",
      eyebrow: "夜色 / 火把之外",
      lead: "争执被火光边缘的动作打断。白色人形伏在地上，眼眶空洞，嘴里模仿着整座城市的虫鸣。",
      sourceRef: summary(55, 55, 7613, 7762),
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["qixia", "lin", "zhao", "xiao"],
      observations: [
        { id: "c6-empty-eyes", label: "空眼眶", text: "苍白人形没有可见眼球，四肢着地，以不协调姿势不断转向。", note: "眼眶状态是可见事实；感知方式尚待判断。", sourceRef: summary(55, 55, 7747, 7757) },
        { id: "c6-cricket-mouth", label: "口中虫鸣", text: "它反复从口中发出“窸窸窣窣”的声音，与城市里的蟋蟀声相同。", note: "虫鸣有了具体来源。", sourceRef: summary(55, 55, 7751, 7761) },
      ],
      dialogue: [],
      canonicalEvent: "众人第一次在火把下看清模仿蟋蟀的人形生物。",
      animationId: "c6-insect-wall",
      advanceLabel: "压住呼吸",
    },
    {
      id: "c6-silent-retreat",
      title: "不要发出声音",
      eyebrow: "黑暗中的撤退",
      lead: "众人不发声、缓慢退入便利店；墙上的怪物避开火光，整夜没有进入灯火通明的室内。玩家必须据此选择移动和庇护点。",
      sourceRef: summary(56, 56, 7763, 7910),
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["qixia", "lin", "zhao", "xiao"],
      observations: [
        { id: "c6-sound-turn", label: "无声撤退", text: "怪物双眼被挖空；众人全程不发声、缓慢退入店内时，它们没有追进来。", note: "齐夏据此判断它们可能通过声音寻找方位。", sourceRef: summary(56, 56, 7765, 7815) },
        { id: "c6-light-edge", label: "避开明处", text: "火把照到墙面时，十多只怪物纷纷爬向黑暗；整夜没有进入灯火通明的便利店。", note: "光照与退避同时发生，因果仍只可暂记。", sourceRef: summary(56, 56, 7777, 7867) },
      ],
      dialogue: [],
      puzzle: {
        id: "c6-retreat-board",
        prompt: "按齐夏当时的判断，选择可能的感知方式、撤退动作和临时庇护点。高声或冲入黑暗会立即进入死亡检查点。",
        requiredObservationIds: ["c6-sound-turn", "c6-light-edge"],
        errorCost: 2,
        solvedText: "齐夏判断怪物可能依靠声音定位；众人压低一切声响缓慢后退，回到亮着灯的便利店。",
        fields: [
          { id: "sense", label: "主要感知", correctValue: "sound", options: [{ value: "sound", label: "声音" }, { value: "vision", label: "视觉" }, { value: "smell", label: "气味" }], wrongMessages: { vision: "它没有眼球，齐夏据此判断它可能用声音寻找方位。", smell: "当前没有气味变化与行动同步的记录。" } },
          { id: "movement", label: "撤退动作", correctValue: "slow-silent", options: [{ value: "slow-silent", label: "缓慢、无声后退" }, { value: "shout-run", label: "大喊后冲刺" }, { value: "dash-dark", label: "冲入更深黑暗" }], wrongMessages: { "shout-run": "大喊会立刻提供精确声源。", "dash-dark": "黑暗中无法观察更多同类，也远离了光线边界。" } },
          { id: "shelter", label: "临时庇护", correctValue: "lit-store", options: [{ value: "lit-store", label: "亮着灯的便利店" }, { value: "dark-alley", label: "无灯小巷" }, { value: "stay-open", label: "停在原地" }], wrongMessages: { "dark-alley": "小巷同时失去灯光与视野，不具备当前安全事实。", "stay-open": "怪物仍在持续搜索声源，原地不是可闭合的庇护。" } },
        ],
        fatalRules: [
          { fieldId: "movement", value: "shout-run", failureId: "insect-hears-you", reason: "你用喊声给空眼眶怪物标出了精确位置；它在你跑出光线前扑到身后。", checkpointSceneId: "c6-silent-retreat" },
          { fieldId: "movement", value: "dash-dark", failureId: "insect-darkness", reason: "你冲进看不见尽头的黑暗，更多“虫鸣”从四周同时靠近。", checkpointSceneId: "c6-silent-retreat" },
        ],
      },
      animationId: "c6-silent-retreat",
      advanceLabel: "沿标记继续找人",
    },
    {
      id: "c6-human-pig-door",
      title: "围棋社门口",
      eyebrow: "第二天 / 人猪入口",
      lead: "墙角符号此刻既可能是S/Z，也可能是5/2。齐夏在围棋社外遇见老吕；对方声称见过一男一女，并提出用一场游戏交换行踪。",
      sourceRef: summary(57, 57, 7911, 8060),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["old-lu", "qixia", "lin", "human-pig"],
      observations: [
        { id: "c6-number-52", label: "墙角符号", text: "符号既像5和2，也像S和Z；齐夏与林檎猜测可能对应李尚武和章晨泽，并沿该方向前进。", note: "此时没有作者、含义或指向的直接证据。", sourceRef: summary(57, 57, 7971, 7993) },
        { id: "c6-old-lu-witness", label: "一男一女", text: "连续追问时，老吕始终描述一名一本正经的男人和一名沉默女子，没有明显改口。", note: "他要求齐夏先赢过围棋社里的人猪。", sourceRef: summary(57, 57, 7995, 8055) },
      ],
      dialogue: [
        { id: "c06-oldlu-001", speakerId: "old-lu", text: "帮我进去，赌赢那只猪。", sourceRef: quote(57, 8025) },
        { id: "c06-qixia-007", speakerId: "qixia", text: "行，我答应了。", sourceRef: quote(57, 8055) },
      ],
      puzzle: {
        id: "c6-door-board",
        prompt: "冻结尚未解开的符号和当前交换条件。",
        requiredObservationIds: ["c6-number-52", "c6-old-lu-witness"],
        errorCost: 1,
        solvedText: "墙角符号继续标为未解；齐夏接受用挑战人猪换取李尚武与章晨泽行踪。",
        fields: [
          { id: "fifty-two", label: "墙角符号当前状态", correctValue: "unresolved", options: [{ value: "unresolved", label: "未解符号" }, { value: "li-message", label: "李尚武的确定留言" }, { value: "exit-code", label: "逃生密码" }], wrongMessages: { "li-message": "两人只是因符号方向继续前进；此时没有留下者或指向对象的直接证据。", "exit-code": "原文此时没有任何逃生密码证据。" } },
          { id: "deal", label: "交换条件", correctValue: "play-for-info", options: [{ value: "play-for-info", label: "替老吕挑战人猪" }, { value: "rob-old-lu", label: "抢走老吕的道" }, { value: "leave", label: "放弃寻找同伴" }], wrongMessages: { "rob-old-lu": "杀人夺道规则仍在，且老吕掌握行踪。", leave: "齐夏此行目的就是找到李尚武和章晨泽。" } },
        ],
      },
      advanceLabel: "推开围棋社的门",
    },
  ],
};

export const chapterSeven: StoryChapterSpec = {
  id: 7,
  slug: "one-hundred-percent",
  title: "百分百",
  subtitle: "棋子、真假话与人猪的赌命",
  source: { startLine: 8061, endLine: 9016, chapters: [58, 59, 60, 61, 62, 63, 64] },
  initialDaoLedger: { qixiaParty: 0, liZhang: 1, oldLu: 5, burned: 96 },
  pressureLimit: 12,
  completionTitle: "第五次扣下扳机",
  completionText: "齐夏赢下两局。老吕用至少五颗已确认存量支付首局门票，十颗奖励归老吕；赌命局以一黑一白和真假话嵌套闭合。人猪回答四次，在第五问后死亡。",
  completionDaoLedger: { qixiaParty: 0, liZhang: 1, oldLu: 10, burned: 96 },
  completionDaoLabel: "齐夏0；李/章起始账1（赛果未核）；老吕本局结算10（更早存量未知）",
  nextChapterId: 8,
  scenes: [
    {
      id: "c7-pig-rules",
      title: "黑白各五十",
      eyebrow: "人猪 / 第一局",
      lead: "老吕此时至少有五颗已确认存量，并从中支付门票。黑白棋子各五十，玩家分入两碗；蒙眼后随机选碗，再随机摸一子。",
      sourceRef: summary(58, 58, 8061, 8200),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["human-pig", "qixia", "old-lu", "lin"],
      observations: [
        { id: "c7-hundred-stones", label: "一百颗棋子", text: "桌面上黑子五十、白子五十，两只瓷碗外观与触感相同。", note: "玩家决定分配，人猪随后打乱碗的位置。", sourceRef: summary(58, 58, 8173, 8183) },
        { id: "c7-oldlu-ticket", label: "至少五颗已确认", text: "老吕当场从自己的口袋取出五颗交给人猪。", note: "只能确认付款前至少持有五颗；更早存量未知。", sourceRef: summary(58, 58, 8163, 8171) },
      ],
      dialogue: [
        { id: "c07-pig-001", speakerId: "human-pig", text: "黑白棋子各五十颗，我要你全部放到这两个碗中。", sourceRef: quote(58, 8177) },
        { id: "c07-qixia-001", speakerId: "qixia", text: "人猪，我小看你了。", sourceRef: quote(58, 8197) },
      ],
      puzzle: {
        id: "c7-rules-board",
        prompt: "先还原随机过程与门票归属，不能把老吕的钱包并入齐夏。",
        requiredObservationIds: ["c7-hundred-stones", "c7-oldlu-ticket"],
        errorCost: 1,
        solvedText: "先随机选碗，再从该碗随机摸子；五颗已确认门票从老吕个人账户扣除。",
        fields: [
          { id: "random-order", label: "随机顺序", correctValue: "bowl-then-stone", options: [{ value: "bowl-then-stone", label: "先选碗，再摸子" }, { value: "stone-then-bowl", label: "先摸子，再选碗" }, { value: "pig-chooses-stone", label: "人猪直接指定棋子" }], wrongMessages: { "stone-then-bowl": "蒙眼后必须先在两只碗中随机选择一只。", "pig-chooses-stone": "人猪只打乱碗，棋子由玩家从所选碗中摸取。" } },
          { id: "ticket-owner", label: "门票账户", correctValue: "old-lu", options: [{ value: "old-lu", label: "老吕个人" }, { value: "qixia", label: "齐夏行动队" }, { value: "li-zhang", label: "李尚武/章晨泽" }], wrongMessages: { qixia: "齐夏当前一颗可支配“道”都没有。", "li-zhang": "李尚武的一颗仍在别处，老吕当场从自己口袋付款。" } },
        ],
      },
      daoLedgerDeltaOnSolve: { oldLu: -5 },
      advanceLabel: "开始分配棋子",
    },
    {
      id: "c7-optimal-split",
      title: "九十九分之七十四",
      eyebrow: "概率板",
      lead: "不能把胜率写成含糊的“约四分之三”。必须给出两碗分配和完整概率。",
      sourceRef: summary(59, 59, 8201, 8328),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["qixia", "human-pig", "old-lu", "lin"],
      observations: [
        { id: "c7-two-identical-bowls", label: "两碗等概率", text: "蒙眼后两只外观相同的碗被打乱，选中任一只的概率都是二分之一。", note: "每只碗必须至少放入一颗。", sourceRef: summary(59, 59, 8221, 8253) },
        { id: "c7-fifty-black", label: "五十颗黑子", text: "总共只有五十颗黑子；把一颗单独放入第一碗后，第二碗剩四十九黑、五十白。", note: "第二碗共九十九颗。", sourceRef: summary(59, 59, 8237, 8269) },
      ],
      dialogue: [
        { id: "c07-qixia-002", speakerId: "qixia", text: "我的分配结束了。", sourceRef: quote(59, 8245) },
        { id: "c07-pig-002", speakerId: "human-pig", text: "你是在跟我耍小聪明吗？", sourceRef: quote(59, 8275) },
      ],
      puzzle: {
        id: "c7-probability-board",
        prompt: "选择最优分配并算出总胜率。",
        requiredObservationIds: ["c7-two-identical-bowls", "c7-fifty-black"],
        errorCost: 2,
        solvedText: "第一碗一颗黑子；第二碗四十九黑五十白。总胜率为 1/2×1 + 1/2×49/99 = 74/99 ≈ 74.747%。",
        fields: [
          { id: "split", label: "两碗分配", correctValue: "one-black-rest", options: [{ value: "one-black-rest", label: "1黑 / 49黑+50白" }, { value: "half-half", label: "25黑25白 / 25黑25白" }, { value: "one-white-rest", label: "1白 / 50黑+49白" }], wrongMessages: { "half-half": "平均分配的总胜率仍是二分之一。", "one-white-rest": "单独放白子会制造一个必败碗。" } },
          { id: "probability", label: "总胜率", correctValue: "74/99", options: [{ value: "1/2", label: "1/2" }, { value: "3/4", label: "3/4" }, { value: "74/99", label: "74/99" }], wrongMessages: { "1/2": "这忽略了一颗黑子的必胜碗。", "3/4": "四分之三是近似直觉，不是严格值；第二碗是49/99而非1/2。" } },
        ],
      },
      animationId: "c7-stone-split",
      advanceLabel: "蒙眼选左碗",
    },
    {
      id: "c7-read-reaction",
      title: "两颗都是黑子",
      eyebrow: "心理战",
      lead: "齐夏从九十九颗的碗里一次抓出两颗并展示给人猪。他自己看不见颜色，只能读取对方的反应。",
      sourceRef: summary(60, 60, 8329, 8419),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["qixia", "human-pig", "old-lu", "lin"],
      observations: [
        { id: "c7-pig-silence", label: "人猪沉默", text: "两颗棋子摊开后，人猪脸色骤变，长时间没有嘲讽、催促或提示。", note: "齐夏仍戴着眼罩。", sourceRef: summary(60, 60, 8339, 8369) },
        { id: "c7-two-in-hand", label: "一次抓两颗", text: "齐夏可以把其中一颗放回、留下一颗作为最终选择。", note: "他要根据人猪反应决定是否保留。", sourceRef: summary(60, 60, 8339, 8381) },
      ],
      dialogue: [
        { id: "c07-qixia-003", speakerId: "qixia", text: "我选完了。", sourceRef: quote(60, 8351) },
        { id: "c07-oldlu-001", speakerId: "old-lu", text: "小子，不是我不想给你，这次是我出的「门票」，所以见谅了。", sourceRef: quote(60, 8397) },
      ],
      puzzle: {
        id: "c7-reaction-board",
        prompt: "人猪的沉默说明什么，齐夏接下来怎么做？",
        requiredObservationIds: ["c7-pig-silence", "c7-two-in-hand"],
        errorCost: 2,
        solvedText: "只有两颗都是黑子，才足以让人猪忘记表演。齐夏留下一颗，首局获胜；十颗奖励进入老吕个人账户。",
        fields: [
          { id: "silence-means", label: "沉默含义", correctValue: "both-black", options: [{ value: "both-black", label: "两颗都是黑子" }, { value: "both-white", label: "两颗都是白子" }, { value: "one-each", label: "一黑一白" }], wrongMessages: { "both-white": "若两颗都白，人猪无需震惊到停止表演。", "one-each": "一黑一白仍可用催促诱导齐夏丢错；沉默会白白泄露信息。" } },
          { id: "action", label: "最终动作", correctValue: "keep-one", options: [{ value: "keep-one", label: "留下一颗，放回一颗" }, { value: "return-both", label: "两颗都放回" }, { value: "show-again", label: "继续抓更多棋子" }], wrongMessages: { "return-both": "已得到两颗均黑的反应证据，全部放回会丢失确定胜局。", "show-again": "规则只要求选择一颗；继续抓取会制造违规风险。" } },
        ],
      },
      animationId: "c7-double-black",
      daoLedgerDeltaOnSolve: { oldLu: 10 },
      advanceLabel: "要求老吕兑现行踪",
    },
    {
      id: "c7-forced-wager",
      title: "不能拒绝的赌命",
      eyebrow: "人猪 / 第二局",
      lead: "人猪点名齐夏赌命。拒绝或逃跑会触发规则制裁；两副眼镜分别强制真假话，佩戴者的具体状态要等回答时确认。",
      sourceRef: summary(60, 61, 8421, 8596),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["human-pig", "qixia", "lin", "old-lu"],
      observations: [
        { id: "c7-wager-mandatory", label: "赌命强制成立", text: "人鼠先前也在不利情况下接受过赌命；老吕明确说被点名的一方必须接受。", note: "朱雀会制裁破坏规则的人。", sourceRef: summary(60, 60, 8421, 8465) },
        { id: "c7-glasses-truth", label: "冷热眼镜", text: "一副眼镜冰凉并强制说假话，另一副灼热并强制说真话。", note: "两名佩戴者知道棋色，齐夏看不见；此刻尚未揭示谁冷谁热。", sourceRef: summary(60, 61, 8471, 8555) },
      ],
      dialogue: [
        { id: "c07-pig-003", speakerId: "human-pig", text: "我要和你再赌一次，这次我要赌命。", sourceRef: quote(60, 8427) },
        { id: "c07-qixia-004", speakerId: "qixia", text: "我拒绝。", sourceRef: quote(60, 8437) },
      ],
      puzzle: {
        id: "c7-wager-board",
        prompt: "冻结赌局能否拒绝，以及两名回答者的真假约束。",
        requiredObservationIds: ["c7-wager-mandatory", "c7-glasses-truth"],
        errorCost: 2,
        solvedText: "赌命不能拒绝。冷眼镜强制假话，热眼镜强制真话；两种约束将成为同一套问法的输入。",
        fields: [
          { id: "decline", label: "是否能拒绝", correctValue: "cannot", options: [{ value: "cannot", label: "不能" }, { value: "can-leave", label: "可以直接离开" }, { value: "pay-more", label: "加钱取消" }], wrongMessages: { "can-leave": "逃跑会破坏赌命规则并招来朱雀制裁。", "pay-more": "赌命签订后没有用“道”赎回的规则。" } },
          { id: "truth-map", label: "眼镜约束", correctValue: "cold-lie-hot-truth", options: [{ value: "cold-lie-hot-truth", label: "冰凉说假 / 灼热说真" }, { value: "cold-truth-hot-lie", label: "冰凉说真 / 灼热说假" }, { value: "both-random", label: "两人随机回答" }], wrongMessages: { "cold-truth-hot-lie": "人猪宣读的冷热规则正好相反：冰凉必须说假，灼热必须说真。", "both-random": "装置会强制真假，不是由回答者自由选择。" } },
        ],
      },
      animationId: "c7-headset-lock",
      advanceLabel: "让人猪挑选棋子",
    },
    {
      id: "c7-force-one-of-each",
      title: "让他替你选择",
      eyebrow: "过度预判",
      lead: "齐夏不求随机公平，而是让人猪相信“由你挑选会让我更容易判断”。对方为了避开预期，只能交出一黑一白。",
      sourceRef: summary(62, 62, 8597, 8746),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["qixia", "human-pig", "lin", "old-lu"],
      observations: [
        { id: "c7-pig-knows-colors", label: "人猪看得见颜色", text: "人猪亲手从黑白棋子中取两颗交给齐夏，并知道每颗的实际颜色。", note: "他也知道齐夏会用语言逆推。", sourceRef: summary(62, 62, 8597, 8665) },
        { id: "c7-overthink", label: "连续反向预判", text: "人猪先拿出两颗白子，又担心齐夏反悔后从剩余棋子重选；两颗黑子会直接交出胜局，于是他改成一黑一白。", note: "人猪以为一黑一白能把胜率维持在二分之一。", sourceRef: summary(62, 62, 8645, 8705) },
      ],
      dialogue: [
        { id: "c07-qixia-005", speakerId: "qixia", text: "你来挑选的话，我就更好判断了。", sourceRef: adaptation(62, 8637) },
      ],
      puzzle: {
        id: "c7-one-each-board",
        prompt: "选择能诱导人猪过度预判的话术，以及最终被交到手中的组合。",
        requiredObservationIds: ["c7-pig-knows-colors", "c7-overthink"],
        errorCost: 2,
        solvedText: "“你挑选会让我更好判断”迫使人猪继续反推，最终亲手交出一黑一白。",
        fields: [
          { id: "induction", label: "诱导话术", correctValue: "you-pick-easier", options: [{ value: "you-pick-easier", label: "你挑选，我更好判断" }, { value: "choose-random", label: "请完全随机" }, { value: "give-two-black", label: "请直接给我两颗黑子" }], wrongMessages: { "choose-random": "随机不会迫使人猪暴露自己的预判。", "give-two-black": "直接说出目标只会让人猪给出相反组合。" } },
          { id: "pair", label: "实际组合", correctValue: "one-black-one-white", options: [{ value: "one-black-one-white", label: "一黑一白" }, { value: "two-black", label: "两黑" }, { value: "two-white", label: "两白" }], wrongMessages: { "two-black": "人猪意识到两黑会直接把胜局交给齐夏，因此没有交出。", "two-white": "人猪先选过两白，却担心齐夏反悔并从剩余棋子重选，因此收回。" } },
        ],
      },
      animationId: "c7-one-each",
      advanceLabel: "向林檎提问",
    },
    {
      id: "c7-nested-question",
      title: "另一个人会怎么说",
      eyebrow: "真假话闭环",
      lead: "齐夏手里一黑一白，只能留下其中一颗。问题必须让真话者和说谎者最终都给出同一方向的反答案。",
      sourceRef: summary(63, 63, 8747, 8890),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["qixia", "lin", "old-lu", "human-pig"],
      observations: [
        { id: "c7-one-black-white", label: "一黑一白", text: "齐夏两只手分别握一颗，且已确认两颗颜色不同。", note: "知道一只手的颜色就能知道另一只。", sourceRef: summary(63, 63, 8747, 8795) },
        { id: "c7-opposite-answer", label: "两层回答", text: "林檎确认自己的眼镜冰凉、必须说假话，因此老吕必须说真话；询问“另一个人会怎么回答”，两条路径都会指向被问棋子的反面。", note: "回答颜色本身不是要保留的颜色。", sourceRef: summary(63, 63, 8775, 8887) },
      ],
      dialogue: [
        { id: "c07-qixia-006", speakerId: "qixia", text: "当我手持两色棋子时，只要像刚才那样提问，便百分之百的知道了手中棋子的颜色。", sourceRef: quote(63, 8873) },
      ],
      puzzle: {
        id: "c7-truth-loop-board",
        prompt: "选出嵌套问法，并决定收到“白色”回答后保留哪一颗。错留另一颗会在正史失败线中死亡。",
        requiredObservationIds: ["c7-one-black-white", "c7-opposite-answer"],
        errorCost: 2,
        solvedText: "问“另一个人会说这颗是什么颜色”。回答永远与被问棋子相反；听到白色，就保留被问的那颗黑子，把另一颗白子交给人猪。",
        fields: [
          { id: "question", label: "提问方式", correctValue: "what-would-other-say", options: [{ value: "what-would-other-say", label: "另一个人会说这颗是什么颜色？" }, { value: "is-this-black", label: "这颗是黑色吗？" }, { value: "which-one-safe", label: "哪颗安全？" }], wrongMessages: { "is-this-black": "直接问只会让真假两人给出相反答案，无法统一。", "which-one-safe": "“安全”不是装置约束的客观棋色，无法构造真值表。" } },
          { id: "keep", label: "听到“白色”后", correctValue: "keep-asked", options: [{ value: "keep-asked", label: "保留被问的棋子" }, { value: "keep-other", label: "保留另一颗棋子" }, { value: "refuse", label: "拒绝交子" }], wrongMessages: { "keep-other": "嵌套回答与被问棋子相反；听到白色说明被问的是黑色。", refuse: "赌命规则已经成立，拒绝交子会触发制裁。" } },
        ],
        fatalRules: [
          { fieldId: "keep", value: "keep-other", failureId: "white-stone", reason: "你把已确定的黑子交给人猪，自己留下白子；揭晓时赌命规则立即执行。", checkpointSceneId: "c7-nested-question" },
          { fieldId: "keep", value: "refuse", failureId: "wager-refusal", reason: "你在赌命局中拒绝交子，规则制裁先于任何逃跑动作降临。", checkpointSceneId: "c7-nested-question" },
        ],
      },
      animationId: "c7-truth-loop",
      advanceLabel: "摘下人猪的面具",
    },
    {
      id: "c7-atonement",
      title: "赎罪的人",
      eyebrow: "四次空膛 / 第五问",
      lead: "人猪摘下面具，用左轮的每一次空膛换一个回答。四条情报必须保持原意；齐夏第五问后离开，不能伪造救援分支。",
      sourceRef: summary(64, 64, 8891, 9016),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["human-pig-unmasked", "qixia", "lin", "old-lu"],
      observations: [
        { id: "c7-four-answers", label: "四次回答", text: "一：为赎罪成为人猪；二：赎罪指修改过去；三：不确定能否出去，但选择留下；四：三千六百颗最慢，探求真相应赢“地”，不要招惹“天”和“龙”。", note: "四次扣动扳机均为空膛。", sourceRef: summary(64, 64, 8951, 8993) },
        { id: "c7-fifth-trigger", label: "第五个问题", text: "齐夏离开前问“你觉得后悔吗”；人猪独自思考后说“谢谢你”，随后枪响。", note: "没有第六个问题，也没有多出的“道”。", sourceRef: summary(64, 64, 8995, 9013) },
      ],
      dialogue: [
        { id: "c07-pig-004", speakerId: "human-pig", text: "因为我要「赎罪」", sourceRef: quote(64, 8965) },
        { id: "c07-qixia-007", speakerId: "qixia", text: "大叔，你觉得后悔吗？", sourceRef: quote(64, 9003) },
        { id: "c07-pig-005", speakerId: "human-pig", text: "谢谢你。", sourceRef: quote(64, 9011) },
      ],
      puzzle: {
        id: "c7-atonement-board",
        prompt: "选择四次回答的完整组合。任何提前解释钟声、生肖来源或“回响”机制的选项都超出本章证据。",
        requiredObservationIds: ["c7-four-answers", "c7-fifth-trigger"],
        errorCost: 2,
        solvedText: "赎罪、修改过去、不确定能否出去但选择留下、三千六百颗最慢、赢“地”并避开“天”和“龙”。齐夏问完第五问离开，人猪固定死亡。",
        fields: [{ id: "answers", label: "四次回答", correctValue: "atonement-past-earth-avoid", options: [{ value: "atonement-past-earth-avoid", label: "赎罪 / 改过去 / 不确定但留下 / 3600最慢、赢地、避天龙" }, { value: "collect-3600", label: "只需收集3600颗" }, { value: "ring-explained", label: "钟声机制已经说明" }], wrongMessages: { "collect-3600": "人猪明确说三千六百颗是最慢的方法。", "ring-explained": "人猪没有解释钟声或异常物证机制。" } }],
      },
      canonicalEvent: "齐夏问完第五个问题后离开；人猪说出“谢谢你”，随后枪响并固定死亡。",
      animationId: "c7-final-shot",
      advanceLabel: "离开空棋社",
    },
  ],
};

export const chapterEight: StoryChapterSpec = {
  id: 8,
  slug: "self-sacrifice",
  title: "舍己",
  subtitle: "空面具、人兔残局与李尚武最后的选择",
  source: { startLine: 9017, endLine: 9968, chapters: [65, 66, 67, 68, 69, 70, 71] },
  initialDaoLedger: { qixiaParty: 0, liZhang: 1, oldLu: 10, burned: 96 },
  pressureLimit: 12,
  completionTitle: "新的四人队",
  completionText: "李尚武以右手和生命救下章晨泽。章晨泽把四颗“道”全部交给齐夏；老吕个人的十颗仍单独记账。三道问题后，四人准备前往地狗游戏。",
  completionDaoLedger: { qixiaParty: 4, liZhang: 0, oldLu: 10, burned: 96 },
  completionDaoLabel: "齐夏可支配4；老吕个人10",
  scenes: [
    {
      id: "c8-empty-mask",
      title: "不要戴上空面具",
      eyebrow: "围棋社残局",
      lead: "人猪没有留下额外的“道”，只留下一副空面具。管理权、考核和冒充后果全部未知；最稳妥的动作不是试戴。",
      sourceRef: summary(65, 65, 9017, 9137),
      backgroundAsset: "/art/chapter-07/go-club-v1.png",
      portraitIds: ["qixia", "old-lu", "lin", "human-pig-unmasked"],
      observations: [
        { id: "c8-no-extra-dao", label: "棋社零余额", text: "抽屉和房间被翻遍，除了老吕已拿到的十颗，棋社没有剩余“道”。", note: "人猪死亡没有产生额外奖励。", sourceRef: summary(65, 65, 9029, 9057) },
        { id: "c8-empty-pig-mask", label: "无人持有的面具", text: "猪面具落在地上；没人知道成为生肖是否需要考核，也不知道谁管理游戏。", note: "老吕想冒充人猪，但尚未戴上。", sourceRef: summary(65, 65, 9059, 9101) },
      ],
      dialogue: [
        { id: "c08-qixia-001", speakerId: "qixia", text: "我劝你不要碰这个东西。", sourceRef: adaptation(65, 9083) },
        { id: "c08-oldlu-001", speakerId: "old-lu", text: "先藏在这吧，做人至少要留一手嘛……", sourceRef: quote(65, 9101) },
      ],
      puzzle: {
        id: "c8-mask-board",
        prompt: "在规则未知时选择可撤回的动作。",
        requiredObservationIds: ["c8-no-extra-dao", "c8-empty-pig-mask"],
        errorCost: 1,
        solvedText: "不戴、不冒充，只把面具藏好。未知管理规则不能用一次试戴去验证。",
        fields: [{ id: "mask-action", label: "面具处理", correctValue: "hide", options: [{ value: "hide", label: "隐藏，不佩戴" }, { value: "wear", label: "立刻戴上营业" }, { value: "destroy", label: "当场焚毁" }], wrongMessages: { wear: "生肖考核和管理者均未知，试戴是不可撤回的越权风险。", destroy: "齐夏只制止佩戴；老吕随后把面具藏进废桌板后，没有将它焚毁。" } }],
      },
      animationId: "c8-mask-hidden",
      advanceLabel: "让老吕带路",
    },
    {
      id: "c8-heavens-mouth",
      title: "诡异的天堂口",
      eyebrow: "张山死亡 / 52仍未解",
      lead: "老吕说张山睡后没再醒来，又讲出天堂口的三层人物。齐夏不能把自己的怀疑写成死因结论。",
      sourceRef: summary(65, 66, 9139, 9256),
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["old-lu", "qixia", "lin", "zhang-shan"],
      observations: [
        { id: "c8-zhang-dead", label: "张山已经死亡", text: "老吕只确认张山早晨不再呼吸；现有伤势、失血和其他袭击都没有被法医结论支持。", note: "齐夏怀疑潇潇或地牛，但仍是怀疑。", sourceRef: summary(66, 66, 9149, 9175) },
        { id: "c8-mouth-ranks", label: "天堂口三层", text: "楚天秋是首领，云瑶是二号，张山是三号；组织第一天就聚集了约二十人。", note: "逃离笔记应在更高层手里。", sourceRef: summary(66, 66, 9177, 9231) },
        { id: "c8-fifty-two-number", label: "许多地方的52", text: "老吕把S/Z看作5/2，只说许多街口都有类似数字。", note: "它仍没有被证明是留言或密码。", sourceRef: summary(66, 66, 9233, 9251) },
      ],
      dialogue: [
        { id: "c08-oldlu-002", speakerId: "old-lu", text: "张山死了。", sourceRef: quote(65, 9139) },
        { id: "c08-oldlu-003", speakerId: "old-lu", text: "我们的组织叫做「天堂口」。", sourceRef: adaptation(66, 9187) },
        { id: "c08-oldlu-004", speakerId: "old-lu", text: "那不是「52」吗？", sourceRef: quote(66, 9243) },
      ],
      puzzle: {
        id: "c8-mouth-board",
        prompt: "固定组织层级、张山死因状态和当前优先目标。",
        requiredObservationIds: ["c8-zhang-dead", "c8-mouth-ranks", "c8-fifty-two-number"],
        errorCost: 2,
        solvedText: "楚天秋一号、云瑶二号、张山三号；张山死因未知，“52”仍未解。当前先找到李尚武。",
        fields: [
          { id: "ranks", label: "天堂口层级", correctValue: "chu-yun-zhang", options: [{ value: "chu-yun-zhang", label: "楚天秋 / 云瑶 / 张山" }, { value: "zhang-chu-yun", label: "张山 / 楚天秋 / 云瑶" }, { value: "yun-zhang-chu", label: "云瑶 / 张山 / 楚天秋" }], wrongMessages: { "zhang-chu-yun": "张山是三号人物，不是首领。", "yun-zhang-chu": "云瑶是二号，楚天秋才是首领。" } },
          { id: "death-cause", label: "张山死因", correctValue: "unknown", options: [{ value: "unknown", label: "未知" }, { value: "xiaoxiao", label: "已证实潇潇所杀" }, { value: "ground-ox", label: "已证实地牛所杀" }], wrongMessages: { xiaoxiao: "齐夏只有动机推测，没有目击或物证。", "ground-ox": "地牛同样只是猜测对象，没有证据闭环。" } },
          { id: "priority", label: "当前优先", correctValue: "find-li", options: [{ value: "find-li", label: "先找李尚武" }, { value: "decode-52", label: "停下破解52" }, { value: "take-mouth", label: "立刻接管天堂口" }], wrongMessages: { "decode-52": "老吕已经指出二人的方向；52此刻既没有含义，也没有可验证入口。", "take-mouth": "齐夏尚未见到楚天秋，也没有接管组织的条件。" } },
        ],
      },
      advanceLabel: "绕过警局街角",
    },
    {
      id: "c8-rabbit-trail",
      title: "新鲜血迹",
      eyebrow: "人兔场地外",
      lead: "人兔试图用陪伴和奖励拖住齐夏，又透露李尚武受伤。地面出现连续新鲜血迹，比任何挑衅都更接近答案。",
      sourceRef: summary(67, 67, 9257, 9385),
      backgroundAsset: "/art/chapter-08/rabbit-escape-room-v1.png",
      portraitIds: ["human-rabbit", "qixia", "lin", "old-lu"],
      observations: [
        { id: "c8-rabbit-delay", label: "人兔的纠缠", text: "人兔提出陪她一天便给“道”和行踪，又承认此前男子受伤。", note: "她没有直接给出李尚武的位置。", sourceRef: summary(67, 67, 9261, 9295) },
        { id: "c8-fresh-blood", label: "向外延伸的血迹", text: "警局外的新鲜血迹一路延伸至药店，屋内传来碰撞声。", note: "出血量沿途持续，却未显示完整伤口规模。", sourceRef: summary(67, 67, 9297, 9325) },
      ],
      dialogue: [
        { id: "c08-rabbit-001", speakerId: "human-rabbit", text: "要玩我的游戏吗？", sourceRef: quote(67, 9269) },
        { id: "c08-rabbit-002", speakerId: "human-rabbit", text: "要自己寻找的话……可得快点呢。", sourceRef: quote(67, 9289) },
        { id: "c08-qixia-002", speakerId: "qixia", text: "我们走吧。", sourceRef: quote(67, 9299) },
      ],
      puzzle: {
        id: "c8-trail-board",
        prompt: "选择最短的可验证路径，不接受人兔提出的新游戏。",
        requiredObservationIds: ["c8-rabbit-delay", "c8-fresh-blood"],
        errorCost: 2,
        solvedText: "拒绝纠缠，沿新鲜血迹前往药店；在那里找到失去整只右手、严重失血的李尚武。",
        fields: [
          { id: "follow", label: "追踪对象", correctValue: "fresh-blood", options: [{ value: "fresh-blood", label: "新鲜血迹" }, { value: "rabbit-game", label: "人兔的新游戏" }, { value: "random-street", label: "随机搜索街区" }], wrongMessages: { "rabbit-game": "人兔只会拖延时间，李尚武的伤势正在恶化。", "random-street": "已有连续血迹提供可验证方向，随机搜索会浪费窗口。" } },
          { id: "destination", label: "血迹终点", correctValue: "pharmacy", options: [{ value: "pharmacy", label: "药店" }, { value: "go-club", label: "围棋社" }, { value: "warehouse", label: "人鼠仓库" }], wrongMessages: { "go-club": "血迹从警局向外延伸，没有返回围棋社。", warehouse: "当前路线没有通向人鼠仓库的证据。" } },
        ],
      },
      animationId: "c8-blood-trail",
      advanceLabel: "进入药店",
    },
    {
      id: "c8-bell-anomaly",
      title: "钟前与钟后",
      eyebrow: "李尚武最后的供述",
      lead: "李尚武承认第一场故事由一个巨大谎言贯穿。钟声再响后，屏幕字样与手中物证发生改变；此刻只能记录差异。",
      sourceRef: summary(67, 68, 9387, 9544),
      backgroundAsset: "/art/chapter-03/ruined-convenience-store-v1.png",
      portraitIds: ["li", "qixia"],
      observations: [
        { id: "c8-screen-word", label: "嫁祸消失", text: "第一次钟响时电子屏出现“嫁祸”；第二次钟响后该字样不再存在。", note: "钟响原因和删改机制仍未知。", sourceRef: summary(68, 68, 9425, 9475) },
        { id: "c8-object-pairs", label: "两组物证", text: "钟前是两根发霉香烟与绿色塑料打火机；钟后出现干净香烟和陈旧金属ZIPPO。", note: "齐夏亲眼见到钟后的物品，却不知道来源。", sourceRef: summary(67, 68, 9387, 9541) },
        { id: "c8-li-confession", label: "重大谎言", text: "李尚武只承认第一场叙述由巨大谎言贯穿，并称这是此生最大的错。", note: "不要自行补写原文未在此处展开的细节。", sourceRef: summary(68, 68, 9485, 9517) },
      ],
      dialogue: [
        { id: "c08-li-001", speakerId: "li", text: "这是此生犯过最大的错……", sourceRef: quote(68, 9505) },
        { id: "c08-li-002", speakerId: "li", text: "齐夏，我死了就是赎罪了……", sourceRef: quote(68, 9535) },
        { id: "c08-qixia-003", speakerId: "qixia", text: "喂……李尚武，你先别死……", sourceRef: quote(68, 9539) },
      ],
      puzzle: {
        id: "c8-anomaly-board",
        prompt: "把钟前、钟后和可下结论严格分开。",
        requiredObservationIds: ["c8-screen-word", "c8-object-pairs", "c8-li-confession"],
        errorCost: 2,
        solvedText: "只记录现象：‘嫁祸’消失，霉烟/塑料火机变为干净烟/金属火机；机制仍未知。李尚武随后死亡。",
        fields: [
          { id: "before", label: "钟响前物证", correctValue: "moldy-plastic", options: [{ value: "moldy-plastic", label: "霉烟 + 绿色塑料火机" }, { value: "clean-zippo", label: "干净烟 + ZIPPO" }, { value: "nothing", label: "没有任何物品" }], wrongMessages: { "clean-zippo": "干净烟和ZIPPO是在钟响后的异常状态中出现。", nothing: "李尚武此前已拿出发霉香烟，并持有绿色塑料打火机。" } },
          { id: "after", label: "钟响后物证", correctValue: "clean-zippo", options: [{ value: "clean-zippo", label: "干净烟 + ZIPPO" }, { value: "moldy-plastic", label: "霉烟 + 绿色塑料火机" }, { value: "dao", label: "额外一颗道" }], wrongMessages: { "moldy-plastic": "这是钟响前被记录的物品组合。", dao: "这一幕没有出现额外“道”。" } },
          { id: "mechanism", label: "机制结论", correctValue: "record-only", options: [{ value: "record-only", label: "只记录，机制未知" }, { value: "echo-explained", label: "已证明回响改写现实" }, { value: "li-trick", label: "李尚武手法掉包" }], wrongMessages: { "echo-explained": "本章没有给出“回响”机制说明。", "li-trick": "齐夏亲眼见到异常发生，且李尚武已濒死，没有掉包证据。" } },
        ],
      },
      animationId: "c8-evidence-swap",
      advanceLabel: "听章晨泽重建兔局",
    },
    {
      id: "c8-rabbit-reconstruction",
      title: "人兔残局重建",
      eyebrow: "事后重建 / 不可改写",
      lead: "这是已经发生的残局，不是让玩家重进人兔游戏。先核人牛的四颗账，再把鱼缸、手铐、钥匙和水阀位置还原。",
      sourceRef: summary(69, 69, 9545, 9684),
      backgroundAsset: "/art/chapter-08/rabbit-escape-room-v1.png",
      portraitIds: ["zhang", "li", "human-rabbit"],
      observations: [
        { id: "c8-ox-runs", label: "三次障碍赛", text: "李尚武用一颗门票参加人牛障碍赛，规则为付一颗、赢两颗，并连续完成三次。", note: "每次净增加一颗。", sourceRef: summary(69, 69, 9593, 9621) },
        { id: "c8-rabbit-layout", label: "四点装置", text: "章晨泽被铁丝绑在注水鱼缸中；李尚武右手被铐在墙边；钥匙在鱼缸里；水阀距李尚武两步。", note: "李尚武手边只有一根木棍。", sourceRef: summary(69, 69, 9625, 9657) },
      ],
      dialogue: [
        { id: "c08-zhang-001", speakerId: "zhang", text: "那一刻，我以为自己死定了。", sourceRef: quote(69, 9659) },
      ],
      puzzle: {
        id: "c8-reconstruction-board",
        prompt: "先计算人牛账，再还原谁、物件与位置。",
        requiredObservationIds: ["c8-ox-runs", "c8-rabbit-layout"],
        errorCost: 2,
        solvedText: "一颗起步，三次每次净增一颗，最终四颗。兔局中章晨泽在注水鱼缸，李尚武被铐；钥匙在缸里，水阀离他两步。",
        fields: [
          { id: "ox-ledger", label: "三次人牛后", correctValue: "4", options: [{ value: "3", label: "3颗" }, { value: "4", label: "4颗" }, { value: "7", label: "7颗" }], wrongMessages: { "3": "每局付1得2是净增1；从1开始三次后为4。", "7": "不能只把三次两颗奖励相加而忽略每次门票。" } },
          { id: "prisoners", label: "两人位置", correctValue: "zhang-tank-li-cuff", options: [{ value: "zhang-tank-li-cuff", label: "章在鱼缸 / 李被手铐" }, { value: "li-tank-zhang-cuff", label: "李在鱼缸 / 章被手铐" }, { value: "both-tank", label: "两人都在鱼缸" }], wrongMessages: { "li-tank-zhang-cuff": "湿透且讲述溺水的是章晨泽；李尚武右手被铐。", "both-tank": "房间两个角落的装置不同。" } },
          { id: "objects", label: "钥匙与水阀", correctValue: "key-tank-valve-two-steps", options: [{ value: "key-tank-valve-two-steps", label: "钥匙在缸 / 水阀距李两步" }, { value: "key-li-valve-tank", label: "钥匙在李手边 / 水阀在缸里" }, { value: "both-reachable", label: "两件物品都伸手可达" }], wrongMessages: { "key-li-valve-tank": "钥匙被放进章晨泽的鱼缸，水阀在李尚武一侧。", "both-reachable": "两步距离正是装置的关键，李尚武无法直接够到水阀。" } },
        ],
      },
      animationId: "c8-water-rise",
      daoLedgerDeltaOnSolve: { liZhang: 3 },
      advanceLabel: "重建李尚武的动作",
    },
    {
      id: "c8-sacrifice-sequence",
      title: "舍弃右手",
      eyebrow: "李尚武的选择",
      lead: "木棍如果先丢向鱼缸，一旦没碎玻璃便永远失去工具。李尚武先尝试脱腕，手铐却越收越紧；剩下的顺序不可改写。",
      sourceRef: summary(70, 70, 9685, 9799),
      backgroundAsset: "/art/chapter-08/rabbit-escape-room-v1.png",
      portraitIds: ["li", "zhang"],
      observations: [
        { id: "c8-cuff-tightens", label: "手铐越收越紧", text: "木棍误击手铐后，外力让手铐进一步收紧；打碎手掌已无法脱出。", note: "鱼缸水位已没过章晨泽脖子。", sourceRef: summary(70, 70, 9687, 9705) },
        { id: "c8-after-release", label: "脱铐后的三步", text: "李尚武脱开后先抵达水阀，再用木棍击碎鱼缸，最后用左手解开铁丝。", note: "他以断手处大量失血为代价完成救援。", sourceRef: summary(70, 70, 9705, 9721) },
      ],
      dialogue: [
        { id: "c08-zhang-002", speakerId: "zhang", text: "正如他所说……他是个警察，所以不能见死不救。", sourceRef: quote(70, 9723) },
      ],
      puzzle: {
        id: "c8-sacrifice-board",
        prompt: "按正史排列从保留木棍到救出章晨泽的完整动作。",
        requiredObservationIds: ["c8-cuff-tightens", "c8-after-release"],
        errorCost: 2,
        solvedText: "保留木棍 → 尝试脱腕失败且手铐收紧 → 舍弃右手脱铐 → 关水阀 → 击碎鱼缸 → 解开铁丝。",
        fields: [
          { id: "first-phase", label: "脱铐阶段", correctValue: "keep-fail-sacrifice", options: [{ value: "keep-fail-sacrifice", label: "留棍 → 失败 → 舍手" }, { value: "throw-stick", label: "先把木棍丢向鱼缸" }, { value: "wait", label: "等待人兔放人" }], wrongMessages: { "throw-stick": "木棍若未击碎玻璃就会落在远处，两人同时失去唯一工具。", wait: "水位持续上升，人兔没有主动终止装置。" } },
          { id: "rescue-phase", label: "救援阶段", correctValue: "valve-glass-wire", options: [{ value: "valve-glass-wire", label: "关阀 → 碎缸 → 解铁丝" }, { value: "glass-wire-valve", label: "碎缸 → 解铁丝 → 关阀" }, { value: "wire-valve-glass", label: "解铁丝 → 关阀 → 碎缸" }], wrongMessages: { "glass-wire-valve": "先关阀可立即停止水位上升，且原文动作顺序明确。", "wire-valve-glass": "章晨泽仍隔着鱼缸，无法先解铁丝。" } },
        ],
      },
      animationId: "c8-hand-sacrifice",
      advanceLabel: "收起异常物证",
    },
    {
      id: "c8-three-questions",
      title: "三个问题",
      eyebrow: "组队条件",
      lead: "章晨泽愿意交出全部四颗并加入。齐夏用三个问题确认她的底线，再要求老吕在游戏中服从指挥。",
      sourceRef: summary(70, 71, 9801, 9968),
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["qixia", "lin", "zhang", "old-lu"],
      observations: [
        { id: "c8-zhang-four", label: "章晨泽的四颗", text: "章晨泽明确说愿意把“道”全部交给齐夏，并用组队换取一起逃离。", note: "四颗来自此前人牛三次净增。", sourceRef: summary(70, 70, 9801, 9823) },
        { id: "c8-three-prompts", label: "三道问题", text: "齐夏依次问逃离理由、是否认可杀人夺道、是否犯过足以改变人生的错误。", note: "章晨泽认可可行性但因法律拒绝实行；第三问没有正面回答。", sourceRef: summary(71, 71, 9855, 9883) },
        { id: "c8-oldlu-order", label: "老吕的承诺", text: "老吕提出四人地狗游戏，并答应比赛中听从齐夏的一切指挥。", note: "他的十颗仍属于个人账户。", sourceRef: summary(71, 71, 9923, 9955) },
      ],
      dialogue: [
        { id: "c08-zhang-003", speakerId: "zhang", text: "齐夏……我可以把「道」都给你。", sourceRef: quote(70, 9809) },
        { id: "c08-qixia-004", speakerId: "qixia", text: "你不得不出去的理由是什么？", sourceRef: quote(71, 9859) },
        { id: "c08-zhang-004", speakerId: "zhang", text: "我觉得这个办法是可行的，但我不想这么做，这触犯了法律。", sourceRef: quote(71, 9865) },
        { id: "c08-oldlu-005", speakerId: "old-lu", text: "你放心啦齐小子，到时候都听你的。", sourceRef: quote(71, 9951) },
      ],
      puzzle: {
        id: "c8-team-board",
        prompt: "固定三问的主题、章晨泽的底线与老吕加入条件。",
        requiredObservationIds: ["c8-zhang-four", "c8-three-prompts", "c8-oldlu-order"],
        errorCost: 2,
        solvedText: "逃离理由 → 杀人夺道底线 → 改变人生的错误。章晨泽交付四颗；老吕同意游戏中服从齐夏，新四人队成立。",
        fields: [
          { id: "questions", label: "三问顺序", correctValue: "exit-kill-mistake", options: [{ value: "exit-kill-mistake", label: "逃离 / 杀人夺道 / 人生错误" }, { value: "dao-mask-bell", label: "道 / 面具 / 钟声" }, { value: "job-age-home", label: "职业 / 年龄 / 家乡" }], wrongMessages: { "dao-mask-bell": "这些是线索，不是齐夏对章晨泽的三道入队问题。", "job-age-home": "齐夏问的是底线与动机，不是身份登记。" } },
          { id: "zhang-line", label: "章晨泽的底线", correctValue: "possible-but-illegal", options: [{ value: "possible-but-illegal", label: "可行，但违法所以不做" }, { value: "impossible", label: "杀人夺道绝不可能" }, { value: "willing", label: "愿意立刻实行" }], wrongMessages: { impossible: "她明确承认理论上可行。", willing: "她明确以法律为由拒绝这样做。" } },
          { id: "oldlu-condition", label: "老吕加入条件", correctValue: "obey-in-game", options: [{ value: "obey-in-game", label: "游戏中服从齐夏" }, { value: "merge-ten", label: "先把十颗并入齐夏" }, { value: "leave", label: "独自离开" }], wrongMessages: { "merge-ten": "本章没有发生十颗转账；那仍是老吕个人钱包。", leave: "老吕提出地狗游戏并主动寻求留下。" } },
        ],
      },
      animationId: "c8-team-form",
      daoLedgerDeltaOnSolve: { qixiaParty: 4, liZhang: -4 },
      advanceLabel: "前往地狗游戏",
    },
  ],
};

export const STORY_CHAPTERS_06_08 = {
  6: chapterSix,
  7: chapterSeven,
  8: chapterEight,
} as const;
