import type { StoryChapterId, StoryChapterSpec, StorySpeakerId } from "./types.ts";

export const STORY_SPEAKER_NAMES: Record<StorySpeakerId, string> = {
  qixia: "齐夏",
  qiao: "乔家劲",
  tiantian: "甜甜",
  lin: "林檎",
  li: "李尚武",
  zhao: "赵海博",
  han: "韩一墨",
  zhang: "章晨泽",
  xiao: "肖冉",
  "store-clerk": "便利店员",
  "human-rat": "人鼠",
  zhuque: "朱雀",
  "ground-ox": "地牛",
  "zhang-shan": "张山",
  "little-glasses": "小眼镜",
};

export const STORY_PORTRAITS: Record<string, string> = {
  qixia: "/art/qixia-v1.png",
  qiao: "/art/qiaojiajin-v1.png",
  tiantian: "/art/tiantian-v2.png",
  lin: "/art/linqin-v1.png",
  li: "/art/lishangwu-v1.png",
  zhao: "/art/zhaohaibo-v1.png",
  han: "/art/hanyimo-v1.png",
  zhang: "/art/zhangchenze-v1.png",
  xiao: "/art/xiaoran-v1.png",
  "store-clerk": "/art/chapter-03/store-clerk-v1.png",
  "human-rat": "/art/chapter-04/human-rat-v1.png",
  zhuque: "/art/chapter-04/zhuque-v1.png",
  "ground-ox": "/art/chapter-05/ground-ox-v1.png",
  "zhang-shan": "/art/chapter-05/zhang-shan-v1.png",
};

const chapterThree: StoryChapterSpec = {
  id: 3,
  slug: "seven-black-sword",
  title: "七黑剑",
  subtitle: "便利店、死者与第一次分队",
  source: { startLine: 3001, endLine: 4142, chapters: [22, 23, 24, 25, 26, 27, 28, 29] },
  initialDao: 4,
  completionTitle: "队伍分开了",
  completionText: "齐夏、乔家劲、甜甜和林檎走向人鼠的仓库。李尚武留在便利店，手里保存着一颗“道”。",
  nextChapterId: 4,
  scenes: [
    {
      id: "c3-store",
      title: "破败便利店",
      eyebrow: "第零天 / 黄昏",
      lead: "韩一墨的肩伤不能再拖。便利店里没有药，只有一个力气异常的瘦弱店员和紧闭的员工休息室。",
      sourceRef: { chapter: 22, lineStart: 3001, lineEnd: 3306 },
      backgroundAsset: "/art/chapter-03/ruined-convenience-store-v1.png",
      portraitIds: ["store-clerk", "qixia", "qiao"],
      observations: [
        { id: "c3-filth", label: "黏黑地面", text: "货架倒塌，地面覆盖新鲜的腥臭、焦味和黏黑污物。", note: "这里一直有别的东西生活。", sourceRef: { chapter: 22, lineStart: 3019, lineEnd: 3045 } },
        { id: "c3-staff-door", label: "员工休息室", text: "门后有翻找声；店员的力量足以拖动数个成年人。", note: "独自跟进去不是交易，是失去退路。", sourceRef: { chapter: 22, lineStart: 3077, lineEnd: 3137 } },
        { id: "c3-hook", label: "鱼钩与鱼线", text: "生锈鱼钩可以磨成弯针，鱼线可用于缝合。", note: "它们是韩一墨此刻唯一的生路。", sourceRef: { chapter: 22, lineStart: 3141, lineEnd: 3163 } },
        { id: "c3-pot", label: "锈锅", text: "锅中食物散发香气；店员反复称它为“小猪崽”。", note: "不要把香味当成安全证据。", sourceRef: { chapter: 23, lineStart: 3183, lineEnd: 3251 } },
      ],
      dialogue: [
        { id: "c03-clerk-001", speakerId: "store-clerk", text: "我这里有啊！有针线的！你跟我来啊！", sourceRef: { chapter: 22, lineStart: 3101, lineEnd: 3101 } },
        { id: "c03-qixia-001", speakerId: "qixia", text: "先去救人，这里我们对付。", sourceRef: { chapter: 23, lineStart: 3211, lineEnd: 3211 } },
      ],
      puzzle: {
        id: "c3-trade",
        prompt: "鱼钩已经拿到，但交易必须留下一个可解释的结果。你怎么处理？",
        requiredObservationIds: ["c3-staff-door", "c3-hook", "c3-pot"],
        errorCost: 1,
        solvedText: "齐夏把一颗“道”留给店员，赵海博立即磨钩、理线并处理韩一墨的伤口。",
        fields: [{
          id: "trade",
          label: "交易决定",
          correctValue: "take-hook-pay-dao",
          options: [
            { value: "follow-alone", label: "独自跟店员进入里屋" },
            { value: "leave-empty", label: "放弃鱼钩，立刻离开" },
            { value: "take-hook-pay-dao", label: "先把鱼钩交给医生，再留下一颗“道”" },
          ],
          wrongMessages: {
            "follow-alone": "店员的力量远超四个成年人；独自进入里屋会失去所有支援。",
            "leave-empty": "韩一墨正在持续失血；没有弯针和线，伤口无法闭合。",
          },
        }],
        fatalRules: [{ fieldId: "trade", value: "follow-alone", failureId: "clerk-room", reason: "你被店员拖进员工休息室，门在同伴赶到前关上。", checkpointSceneId: "c3-store" }],
      },
      animationId: "c3-hook-trade",
      daoDeltaOnSolve: -1,
      advanceLabel: "处理伤口，熬过黑夜",
    },
    {
      id: "c3-night",
      title: "伸手不见五指",
      eyebrow: "第零天 / 深夜",
      lead: "赵海博在没有麻药的情况下完成缝合。黑夜吞没整座城市，所有人都在饥饿中睡去。",
      sourceRef: { chapter: 24, lineStart: 3307, lineEnd: 3754 },
      backgroundAsset: "/art/chapter-03/ruined-convenience-store-v1.png",
      portraitIds: ["han", "zhao", "qixia"],
      observations: [
        { id: "c3-old-title", label: "离群之刺", text: "韩一墨坚持把阿卡丽称为“暗影之拳”，赵海博却只知道“离群之刺”。", note: "两人的常识像来自不同时间。", sourceRef: { chapter: 24, lineStart: 3319, lineEnd: 3365 } },
        { id: "c3-darkness", label: "绝对黑夜", text: "城里没有路灯，黑到无法确认眼睛是否睁开。", note: "所有人最终都失去了对环境的监视。", sourceRef: { chapter: 26, lineStart: 3601, lineEnd: 3659 } },
      ],
      dialogue: [
        { id: "c03-han-001", speakerId: "han", text: "没事……至少我能活下来，对吧？", sourceRef: { chapter: 23, lineStart: 3237, lineEnd: 3237 } },
        { id: "c03-qixia-002", speakerId: "qixia", text: "小安，我马上就会从这个鬼地方逃出去。你等着。", sourceRef: { chapter: 26, lineStart: 3595, lineEnd: 3595 } },
      ],
      canonicalEvent: "黎明钟响后，韩一墨被一把通体漆黑的巨剑钉在地面，随后死亡。这个事件不可被玩家提前阻止。",
      animationId: "c3-bell-sword",
      advanceLabel: "钟声响起",
    },
    {
      id: "c3-sword",
      title: "死者与七黑剑",
      eyebrow: "第一天 / 黎明",
      lead: "韩一墨临死叫出齐夏，又反复说“七黑剑不可能”。不要靠情绪指认凶手，先检查他不可能知道的事。",
      sourceRef: { chapter: 27, lineStart: 3755, lineEnd: 3892 },
      backgroundAsset: "/art/chapter-03/ruined-convenience-store-v1.png",
      portraitIds: ["qixia", "zhang", "xiao"],
      observations: [
        { id: "c3-ceiling", label: "完好天花板", text: "天花板没有破口，巨剑不是从上方坠落。", note: "“天降”解释不成立。", sourceRef: { chapter: 26, lineStart: 3701, lineEnd: 3707 } },
        { id: "c3-weight", label: "一百五十斤", text: "齐夏与乔家劲合力拔剑，估算它约有一百五十斤。", note: "凶器不可能被悄无声息藏在普通人身上。", sourceRef: { chapter: 27, lineStart: 3781, lineEnd: 3791 } },
        { id: "c3-engraving", label: "剑柄背面", text: "“七黑剑”刻在死者视线的另一侧。", note: "受击后第一次睁眼的人看不到这三个字。", sourceRef: { chapter: 27, lineStart: 3795, lineEnd: 3813 } },
        { id: "c3-last-words", label: "最后的话", text: "韩一墨两次提到“七黑剑”，却没有说出刺杀者。", note: "他惊讶的是凶器本身。", sourceRef: { chapter: 27, lineStart: 3815, lineEnd: 3831 } },
      ],
      dialogue: [
        { id: "c03-han-002", speakerId: "han", text: "这地方不对劲……这把七黑剑绝对不可能……", sourceRef: { chapter: 26, lineStart: 3711, lineEnd: 3711 } },
        { id: "c03-qixia-003", speakerId: "qixia", text: "韩一墨有可能认识那把剑。", sourceRef: { chapter: 29, lineStart: 4021, lineEnd: 4021 } },
      ],
      puzzle: {
        id: "c3-sword-board",
        prompt: "闭合七黑剑证据板。这里能证明的是“认知矛盾”，不是凶手身份。",
        requiredObservationIds: ["c3-ceiling", "c3-weight", "c3-engraving", "c3-last-words"],
        errorCost: 1,
        solvedText: "韩一墨在看不到铭文的位置说出了剑名。他很可能早已认识七黑剑；叫出齐夏不能单独证明齐夏杀人。",
        fields: [
          { id: "physical", label: "凶器的物理事实", correctValue: "heavy-intact-ceiling", options: [{ value: "fell-from-ceiling", label: "巨剑从天花板坠落" }, { value: "hidden-by-qixia", label: "齐夏把巨剑藏在身上" }, { value: "heavy-intact-ceiling", label: "剑极重，且天花板完整" }], wrongMessages: { "fell-from-ceiling": "天花板没有任何破口。", "hidden-by-qixia": "一百五十斤的一人高巨剑无法藏在普通衣物内。" } },
          { id: "knowledge", label: "最关键的矛盾", correctValue: "knew-unseen-name", options: [{ value: "called-qixia", label: "死者叫了齐夏" }, { value: "knew-unseen-name", label: "死者说出视线外的剑名" }, { value: "no-last-words", label: "死者没有留下任何信息" }], wrongMessages: { "called-qixia": "叫出齐夏只证明他想和齐夏说话，不能证明刺杀者。", "no-last-words": "原文明确留下了“七黑剑不可能”。" } },
          { id: "inference", label: "当前能成立的结论", correctValue: "han-knew-sword", options: [{ value: "qixia-killer", label: "齐夏就是凶手" }, { value: "clerk-proven", label: "店员已被证明是凶手" }, { value: "han-knew-sword", label: "韩一墨此前认识七黑剑" }], wrongMessages: { "qixia-killer": "证据不足；这是肖冉的情绪判断。", "clerk-proven": "店员有力量，但现有线索没有证明她实施了刺杀。" } },
        ],
      },
      animationId: "c3-sword-board",
      advanceLabel: "决定分队与道的归属",
    },
    {
      id: "c3-split",
      title: "分道扬镳",
      eyebrow: "第一天 / 清晨",
      lead: "八个人分成留守与探索两队。你必须同时冻结人员、伤情和三颗剩余的“道”。",
      sourceRef: { chapter: 25, lineStart: 3437, lineEnd: 4008 },
      backgroundAsset: "/art/chapter-02/termination-plaza-v1.png",
      portraitIds: ["qixia", "qiao", "tiantian", "lin"],
      observations: [
        { id: "c3-factions", label: "灰色阵营", text: "甜甜指出一道无形的墙：骗子、混混、陪酒小姐站在同一侧。", note: "林檎主动越过这道墙。", sourceRef: { chapter: 25, lineStart: 3523, lineEnd: 3565 } },
        { id: "c3-dao-ledger", label: "剩余三颗道", text: "四颗“道”中有一颗已用于鱼钩和鱼线。", note: "探索仍需要筹码，留守队也得到一颗。", sourceRef: { chapter: 28, lineStart: 3893, lineEnd: 3997 } },
      ],
      dialogue: [
        { id: "c03-tiantian-001", speakerId: "tiantian", text: "墙的那一侧，是警察、律师、医生、作家；这一侧，是骗子、混混、妓女。", sourceRef: { chapter: 25, lineStart: 3539, lineEnd: 3539 } },
        { id: "c03-qixia-004", speakerId: "qixia", text: "暂且寄存在你那里。那一颗给你，我手里的两颗就干净了。", sourceRef: { chapter: 28, lineStart: 3995, lineEnd: 3995 } },
      ],
      puzzle: {
        id: "c3-split-board",
        prompt: "固定探索队、留守队和剩余筹码。",
        requiredObservationIds: ["c3-factions", "c3-dao-ledger"],
        errorCost: 1,
        solvedText: "探索队：齐夏、乔家劲、甜甜、林檎。留守队：李尚武、赵海博、肖冉、章晨泽。李尚武保存一颗，齐夏带走两颗。",
        fields: [
          { id: "explorers", label: "探索队", correctValue: "qixia-qiao-tiantian-lin", options: [{ value: "qixia-qiao-tiantian-lin", label: "齐夏 / 乔家劲 / 甜甜 / 林檎" }, { value: "qixia-qiao-li-zhao", label: "齐夏 / 乔家劲 / 李尚武 / 赵海博" }, { value: "all-eight", label: "八人继续同行" }], wrongMessages: { "qixia-qiao-li-zhao": "李尚武与赵海博选择留守；林檎主动加入齐夏。", "all-eight": "韩一墨死亡后，队伍在便利店正式分裂。" } },
          { id: "dao", label: "三颗道的分配", correctValue: "li-one-qixia-two", options: [{ value: "qixia-three", label: "齐夏全部带走" }, { value: "li-two-qixia-one", label: "李尚武两颗，齐夏一颗" }, { value: "li-one-qixia-two", label: "李尚武一颗，齐夏两颗" }], wrongMessages: { "qixia-three": "齐夏最终主动抛给李尚武一颗。", "li-two-qixia-one": "争执结束后只交给留守队一颗。" } },
        ],
      },
      animationId: "c3-team-split",
      advanceLabel: "返回广场",
    },
    {
      id: "c3-echo",
      title: "钟与回响",
      eyebrow: "第一天 / 广场",
      lead: "电子屏上的句子已经消失。钟声不是所有死者的丧钟；枯槁老人却认出这支队伍，并提到赌命与天龙。",
      sourceRef: { chapter: 29, lineStart: 4009, lineEnd: 4142 },
      backgroundAsset: "/art/chapter-02/termination-plaza-v1.png",
      portraitIds: ["qixia", "qiao", "tiantian", "lin"],
      observations: [
        { id: "c3-bell", label: "两次钟声", text: "人羊打碎男人头颅、韩一墨死亡时都响过钟；但上千房间的死亡并未让钟持续鸣响。", note: "钟声触发条件仍未知。", sourceRef: { chapter: 29, lineStart: 4051, lineEnd: 4083 } },
        { id: "c3-elder", label: "枯槁老人", text: "老人说答案是赌命，又因众人见过天龙而绝望。", note: "他像是认识曾经的齐夏与乔家劲。", sourceRef: { chapter: 29, lineStart: 4091, lineEnd: 4141 } },
      ],
      dialogue: [
        { id: "c03-qiao-001", speakerId: "qiao", text: "冚家铲，又是疯子。总感觉待久了，我们也会疯掉。", sourceRef: { chapter: 30, lineStart: 4145, lineEnd: 4145 } },
      ],
      advanceLabel: "走向人鼠的仓库",
    },
  ],
};

const chapterFour: StoryChapterSpec = {
  id: 4,
  slug: "warehouse-search",
  title: "仓库寻道",
  subtitle: "人鼠、赌命与朱雀",
  source: { startLine: 4143, endLine: 4986, chapters: [30, 31, 32, 33, 34, 35] },
  initialDao: 2,
  completionTitle: "先探规则，再赌命",
  completionText: "队伍拒绝杀人夺道。齐夏冻结新的战术：同伴先确认规则，他在有把握后赌命。",
  nextChapterId: 5,
  scenes: [
    {
      id: "c4-rules",
      title: "人鼠的安全游戏",
      eyebrow: "第一天 / 鼠类考验",
      lead: "门票一颗“道”。一个人进入仓库，五分钟内找到一颗“道”便获胜；失败只损失门票。越安全，越像陷阱。",
      sourceRef: { chapter: 30, lineStart: 4143, lineEnd: 4288 },
      backgroundAsset: "/art/chapter-04/warehouse-v1.png",
      portraitIds: ["human-rat", "tiantian", "qixia"],
      observations: [
        { id: "c4-now", label: "规则里的“现在”", text: "人鼠每次都先站进仓库，才说“现在这个房间中有一个道”。", note: "这句话只保证宣读规则的瞬间。", sourceRef: { chapter: 30, lineStart: 4241, lineEnd: 4255 } },
        { id: "c4-safe", label: "没有死亡惩罚", text: "失败只损失一颗门票；获胜也只得到一颗。", note: "常规下注不会产生净收益。", sourceRef: { chapter: 30, lineStart: 4257, lineEnd: 4275 } },
      ],
      dialogue: [
        { id: "c04-rat-001", speakerId: "human-rat", text: "现在这个房间中有一个道，五分钟之内找到，它就归你们。", sourceRef: { chapter: 30, lineStart: 4247, lineEnd: 4247 } },
        { id: "c04-tiantian-001", speakerId: "tiantian", text: "我可以先去试试。死了也没事。", sourceRef: { chapter: 30, lineStart: 4277, lineEnd: 4277 } },
      ],
      puzzle: {
        id: "c4-first-search",
        prompt: "第一次搜索必须复刻甜甜实际执行的验证顺序。",
        requiredObservationIds: ["c4-now", "c4-safe"],
        errorCost: 1,
        solvedText: "甜甜推倒货架、踩开纸箱、关灯寻找微光，最后检查罐头，但五分钟到时仍一无所获。",
        fields: [
          { id: "tester", label: "第一位参与者", correctValue: "tiantian", options: [{ value: "qixia", label: "齐夏" }, { value: "qiao", label: "乔家劲" }, { value: "tiantian", label: "甜甜" }], wrongMessages: { qixia: "原著中齐夏先在门外观察规则漏洞。", qiao: "乔家劲想第二次进入，但被齐夏拦住。" } },
          { id: "method", label: "搜索方法", correctValue: "scatter-dark-cans", options: [{ value: "one-box-at-time", label: "逐箱慢慢翻找" }, { value: "scatter-dark-cans", label: "推倒货架、关灯找光、再看罐头" }, { value: "grab-rat", label: "开局抓住人鼠" }], wrongMessages: { "one-box-at-time": "上百个箱子无法在五分钟内逐个检查。", "grab-rat": "第一次参与者是甜甜，她还没有确认裁判与“道”的关系。" } },
        ],
      },
      daoDeltaOnSolve: -1,
      animationId: "c4-warehouse-dark",
      advanceLabel: "复盘失败的五分钟",
    },
    {
      id: "c4-deduction",
      title: "道不在仓库里",
      eyebrow: "第二次下注前",
      lead: "房间复原得崭新如初。人鼠再次走进门内，重复同一句规则。把她的措辞与她知道失败的方式放在一起。",
      sourceRef: { chapter: 31, lineStart: 4289, lineEnd: 4586 },
      backgroundAsset: "/art/chapter-04/warehouse-v1.png",
      portraitIds: ["qixia", "human-rat", "qiao"],
      observations: [
        { id: "c4-no-glow", label: "黑暗中没有光", text: "所有箱子散落、灯被关闭，仓库中没有任何“道”的微光。", note: "密封罐头只是可能性，不是答案。", sourceRef: { chapter: 31, lineStart: 4341, lineEnd: 4377 } },
        { id: "c4-knows", label: "裁判提前知道失败", text: "门始终关闭，人鼠打开门的瞬间便宣布失败。", note: "她无需检查现场，因为她知道里面不可能有“道”。", sourceRef: { chapter: 32, lineStart: 4503, lineEnd: 4513 } },
        { id: "c4-reset", label: "房间完全复原", text: "货架、箱子和罐头在第二局前全部回到原位。", note: "寻找行为不会永久改变场地。", sourceRef: { chapter: 31, lineStart: 4411, lineEnd: 4427 } },
      ],
      dialogue: [
        { id: "c04-qixia-001", speakerId: "qixia", text: "这一次，我要赌命。", sourceRef: { chapter: 31, lineStart: 4445, lineEnd: 4445 } },
        { id: "c04-qixia-002", speakerId: "qixia", text: "我找到了。", sourceRef: { chapter: 32, lineStart: 4479, lineEnd: 4479 } },
      ],
      puzzle: {
        id: "c4-rule-trap",
        prompt: "决定下注前，把规则漏洞完整闭合。赌命但找错位置会真正死亡。",
        requiredObservationIds: ["c4-no-glow", "c4-knows", "c4-reset"],
        errorCost: 1,
        solvedText: "“现在”只覆盖人鼠仍在房间内的时刻。她关门离开时把“道”一起带走；开局瞬间应从她的上衣口袋取出目标。",
        fields: [
          { id: "wording", label: "规则漏洞", correctValue: "now-only", options: [{ value: "five-minutes", label: "五分钟其实只有十秒" }, { value: "now-only", label: "“现在”只保证宣读时存在" }, { value: "cans", label: "所有罐头都需要打开" }], wrongMessages: { "five-minutes": "甜甜实际得到完整五分钟。", cans: "罐头没有解释人鼠为何不用查看就知道失败。" } },
          { id: "location", label: "第二局开局目标", correctValue: "rat-pocket", options: [{ value: "rat-pocket", label: "人鼠的上衣口袋" }, { value: "sealed-can", label: "密封蚕豆罐头" }, { value: "light-switch", label: "灯开关内部" }], wrongMessages: { "sealed-can": "关门后仓库中根本没有“道”。", "light-switch": "开关只帮助验证黑暗中没有微光。" } },
          { id: "wager", label: "下注", correctValue: "life", options: [{ value: "one-dao", label: "再付一颗道" }, { value: "life", label: "赌上齐夏的命" }, { value: "none", label: "要求免费重赛" }], wrongMessages: { "one-dao": "一换一不会产生净收益，也无法迫使裁判承担同等赌注。", none: "人鼠没有义务免费重赛。" } },
        ],
        fatalRules: [
          { fieldId: "location", value: "sealed-can", when: { wager: "life" }, failureId: "empty-warehouse", reason: "你赌上性命后冲向罐头。门关闭时仓库中没有“道”，五分钟后赌约执行。", checkpointSceneId: "c4-deduction" },
          { fieldId: "location", value: "light-switch", when: { wager: "life" }, failureId: "empty-warehouse", reason: "你赌上性命后拆开灯钮。真正的“道”已经随人鼠离开房间。", checkpointSceneId: "c4-deduction" },
        ],
      },
      daoDeltaOnSolve: 4,
      animationId: "c4-pocket-reveal",
      advanceLabel: "面对赌命的结果",
    },
    {
      id: "c4-verdict",
      title: "朱雀执行规则",
      eyebrow: "赌命 / 对等赌注",
      lead: "齐夏要求放过人鼠，但朱雀并不接受。人鼠违反规则并试图逃跑，她的死亡无法被这场胜利撤销。",
      sourceRef: { chapter: 33, lineStart: 4587, lineEnd: 4730 },
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["zhuque", "human-rat", "qixia"],
      observations: [
        { id: "c4-symmetric", label: "对等赌注", text: "参与者赌命，生肖也必须以命对应。", note: "赌命不是单方面加码。", sourceRef: { chapter: 33, lineStart: 4591, lineEnd: 4627 } },
        { id: "c4-rule-enforcer", label: "规则执行者", text: "朱雀可以瞬间移动并制服人鼠，却声称自己也受更高规则限制。", note: "终焉之地存在强于生肖的管理层级。", sourceRef: { chapter: 33, lineStart: 4631, lineEnd: 4687 } },
        { id: "c4-real-name", label: "张丽娟", text: "朱雀准确叫出齐夏、乔家劲、林檎和甜甜的本名。", note: "管理者掌握参与者身份。", sourceRef: { chapter: 33, lineStart: 4661, lineEnd: 4673 } },
      ],
      dialogue: [
        { id: "c04-zhuque-001", speakerId: "zhuque", text: "逃跑可不行。你要乖一点，赌命就是赌命。", sourceRef: { chapter: 33, lineStart: 4617, lineEnd: 4617 } },
        { id: "c04-rat-002", speakerId: "human-rat", text: "这里谁又不是参与者呢……我宁可从未戴上鼠的面具。", sourceRef: { chapter: 33, lineStart: 4713, lineEnd: 4713 } },
      ],
      canonicalEvent: "人鼠死亡并交出返还门票与三颗自有“道”，队伍总数达到五颗。",
      animationId: "c4-zhuque-arrival",
      advanceLabel: "整理新规则",
    },
    {
      id: "c4-strategy",
      title: "试探队友",
      eyebrow: "人鼠死后",
      lead: "齐夏提出“杀人夺道”。这不是最终方案，而是一次对三名队友底线的测试。",
      sourceRef: { chapter: 34, lineStart: 4731, lineEnd: 4832 },
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["qixia", "qiao", "tiantian", "lin"],
      observations: [
        { id: "c4-fairness", label: "诡异的公平", text: "朱雀维护赌局、又受规则限制；裁判希望参与者死在游戏里，而非被随意杀死。", note: "杀人夺道可能违反更高规则。", sourceRef: { chapter: 34, lineStart: 4777, lineEnd: 4813 } },
      ],
      dialogue: [
        { id: "c04-qiao-001", speakerId: "qiao", text: "我不会帮你。就算天塌下来，我也不会做不义的事。", sourceRef: { chapter: 34, lineStart: 4771, lineEnd: 4771 } },
        { id: "c04-qixia-003", speakerId: "qixia", text: "很好，如今我可以放心告诉你们我真正的计划了。", sourceRef: { chapter: 34, lineStart: 4795, lineEnd: 4795 } },
      ],
      puzzle: {
        id: "c4-team-test",
        prompt: "记录队友的底线，并冻结真正的获道战术。",
        requiredObservationIds: ["c4-fairness"],
        errorCost: 1,
        solvedText: "乔家劲、林檎和甜甜都拒绝杀人夺道。真正方案是先由同伴探明规则，齐夏有把握后再赌命，收益平分。",
        fields: [
          { id: "response", label: "三人的共同回答", correctValue: "reject-killing", options: [{ value: "accept-killing", label: "同意杀人夺道" }, { value: "reject-killing", label: "拒绝杀人夺道" }, { value: "qiao-only", label: "只有乔家劲拒绝" }], wrongMessages: { "accept-killing": "三人都明确拒绝；这是齐夏继续合作的前提。", "qiao-only": "林檎与甜甜同样拒绝。" } },
          { id: "plan", label: "真正战术", correctValue: "scout-then-life", options: [{ value: "murder", label: "寻找落单者抢道" }, { value: "all-bet-life", label: "四人每局一起赌命" }, { value: "scout-then-life", label: "同伴探规则，齐夏确认后赌命" }], wrongMessages: { murder: "杀人夺道只是试探，不是计划。", "all-bet-life": "四人同时赌命会放大无法回收的风险。" } },
        ],
      },
      animationId: "c4-team-oath",
      advanceLabel: "继续深入城市",
    },
    {
      id: "c4-leaflet",
      title: "传单是什么",
      eyebrow: "第一天 / 城市深处",
      lead: "原住民递来一张陈旧广告。林檎却不知道“传单”是什么；齐夏没有得到答案，只把异常记入长期档案。",
      sourceRef: { chapter: 35, lineStart: 4833, lineEnd: 4986 },
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["lin", "qixia", "qiao"],
      observations: [
        { id: "c4-leaflet-fact", label: "常识缺口", text: "林檎认真询问“传单是什么”，且不认为自己的问题异常。", note: "这里只记录事实，不提前解释她的身份。", sourceRef: { chapter: 35, lineStart: 4891, lineEnd: 4955 } },
        { id: "c4-glasses", label: "眼镜男招手", text: "街对面的眼镜男称他们为“良人”，并邀请四人参加需要二十人的牛类游戏。", note: "下一场游戏承诺大量“道”。", sourceRef: { chapter: 35, lineStart: 4957, lineEnd: 4985 } },
      ],
      dialogue: [
        { id: "c04-lin-001", speakerId: "lin", text: "传单是什么？", sourceRef: { chapter: 35, lineStart: 4899, lineEnd: 4899 } },
        { id: "c04-glasses-001", speakerId: "little-glasses", text: "我们找到个不错的游戏，有没有兴趣一起赚点道？", sourceRef: { chapter: 35, lineStart: 4979, lineEnd: 4979 } },
      ],
      advanceLabel: "接受地牛的邀请",
    },
  ],
};

const chapterFive: StoryChapterSpec = {
  id: 5,
  slug: "ground-ox",
  title: "地牛",
  subtitle: "十分钟、黑熊与圆形铁板",
  source: { startLine: 4987, endLine: 6744, chapters: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48] },
  initialDao: 5,
  completionTitle: "大脑与拳头",
  completionText: "四人带着九十六颗“道”和一条熊臂离开。张山留下逃离者笔记的地址，而可疑的独行女子在背后露出真实神色。",
  scenes: [
    {
      id: "c5-entry",
      title: "二十人的地牛游戏",
      eyebrow: "第一天 / 牛类考验",
      lead: "每人门票一颗“道”，二十人随机分成黄绿两队。坚持十分钟的每位幸存者，都得到与总通关人数相同的“道”。",
      sourceRef: { chapter: 36, lineStart: 4987, lineEnd: 5256 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["ground-ox", "qixia", "qiao"],
      observations: [
        { id: "c5-reward", label: "奖励公式", text: "若十九人通关，每名幸存者都得到十九颗“道”。", note: "总收益随幸存人数增长。", sourceRef: { chapter: 36, lineStart: 5025, lineEnd: 5041 } },
        { id: "c5-random", label: "随机分队", text: "齐夏、乔家劲进入黄队；甜甜、林檎进入绿队。", note: "两场独立进行，无法互相支援。", sourceRef: { chapter: 37, lineStart: 5173, lineEnd: 5225 } },
      ],
      dialogue: [
        { id: "c05-ox-001", speakerId: "ground-ox", text: "双方独立进行游戏。坚持十分钟不被淘汰，则视为过关。", sourceRef: { chapter: 37, lineStart: 5205, lineEnd: 5205 } },
        { id: "c05-qiao-001", speakerId: "qiao", text: "终于轮到我表现了。", sourceRef: { chapter: 36, lineStart: 5081, lineEnd: 5081 } },
      ],
      puzzle: {
        id: "c5-entry-board",
        prompt: "支付四人的门票，并锁定随机分队结果。",
        requiredObservationIds: ["c5-reward", "c5-random"],
        errorCost: 1,
        solvedText: "四颗“道”投入票箱。齐夏与乔家劲进入黄门，甜甜与林檎进入绿门。",
        fields: [
          { id: "tickets", label: "门票总数", correctValue: "four", options: [{ value: "one", label: "一颗" }, { value: "four", label: "四颗" }, { value: "five", label: "五颗" }], wrongMessages: { one: "四名队员都参加，每人一颗。", five: "队伍只有四人参加；第五颗留作最后筹码。" } },
          { id: "teams", label: "分队", correctValue: "qixia-qiao-yellow", options: [{ value: "all-yellow", label: "四人同在黄队" }, { value: "qixia-qiao-yellow", label: "齐夏乔家劲黄队，甜甜林檎绿队" }, { value: "qixia-alone", label: "齐夏独自进入黄队" }], wrongMessages: { "all-yellow": "灯光随机分队，两个女孩亮起绿灯。", "qixia-alone": "乔家劲与齐夏同时亮起黄灯。" } },
        ],
      },
      daoDeltaOnSolve: -4,
      animationId: "c5-team-lights",
      advanceLabel: "走进黄色场地",
    },
    {
      id: "c5-arena",
      title: "黑色来客",
      eyebrow: "倒计时 10:00",
      lead: "铁门升起，饥饿黑熊进入场地。一名参与者听信“遇熊装死”，当场被杀。你要从场地里找出唯一可重复使用的工具。",
      sourceRef: { chapter: 38, lineStart: 5257, lineEnd: 5534 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["qixia", "qiao"],
      observations: [
        { id: "c5-black-bear", label: "胸口白月牙", text: "这是体型异常巨大的黑熊，不是棕熊。", note: "饥饿黑熊会把装死的人当成食物。", sourceRef: { chapter: 38, lineStart: 5299, lineEnd: 5359 } },
        { id: "c5-plate", label: "中央圆铁板", text: "场地空旷，唯一人为放置的物件是一块桌面大小的沉重圆铁板。", note: "它没有机关或文字，但可以立起并滚动。", sourceRef: { chapter: 38, lineStart: 5391, lineEnd: 5401 } },
      ],
      dialogue: [
        { id: "c05-qixia-001", speakerId: "qixia", text: "如果遇到棕熊，装死还有一线生机，可黑熊不行！快起来跑！", sourceRef: { chapter: 38, lineStart: 5341, lineEnd: 5341 } },
        { id: "c05-qiao-002", speakerId: "qiao", text: "骗人仔！我这条烂命可交给你了！", sourceRef: { chapter: 39, lineStart: 5415, lineEnd: 5415 } },
      ],
      puzzle: {
        id: "c5-first-response",
        prompt: "决定齐夏自己的应对与工具。NPC 的错误会保留原著第一名死者，但玩家不必重复她的错误。",
        requiredObservationIds: ["c5-black-bear", "c5-plate"],
        errorCost: 1,
        solvedText: "齐夏命令众人跑动，并让乔家劲拖住黑熊；自己冲向中央铁板。",
        fields: [
          { id: "bear-response", label: "面对黑熊", correctValue: "run-and-face", options: [{ value: "play-dead", label: "原地装死" }, { value: "run-and-face", label: "保持面对，拉开距离" }, { value: "climb-wall", label: "徒手攀爬高墙" }], wrongMessages: { "play-dead": "饥饿黑熊会进食人类；装死已造成第一名参与者死亡。", "climb-wall": "四面高墙没有抓点，楼梯已经消失。" } },
          { id: "tool", label: "场地工具", correctValue: "iron-plate", options: [{ value: "iron-plate", label: "中央圆铁板" }, { value: "gate", label: "关闭的铁门" }, { value: "chair", label: "不存在的椅子" }], wrongMessages: { gate: "铁门由场外控制，参与者无法开启。", chair: "椅子留在分队房，场地内没有。" } },
        ],
        fatalRules: [{ fieldId: "bear-response", value: "play-dead", failureId: "black-bear-feeding", reason: "你在饥饿黑熊面前装死。它俯身确认气味后咬住了你的脖颈。", checkpointSceneId: "c5-arena" }],
      },
      animationId: "c5-bear-gate",
      advanceLabel: "立起圆铁板",
    },
    {
      id: "c5-formation",
      title: "老鹰捉小鸡",
      eyebrow: "倒计时 07:00",
      lead: "铁板只能勉强挡住一个人，却可以滚动。把“防御敌人”和“保护队友”转换成童年游戏的阵型。",
      sourceRef: { chapter: 39, lineStart: 5403, lineEnd: 5822 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["qiao", "qixia"],
      observations: [
        { id: "c5-roll", label: "圆板可滚动", text: "铁板很重、无把手，平举不可行；立起后可以沿地面改变方向。", note: "正面承力者会失去视野。", sourceRef: { chapter: 40, lineStart: 5573, lineEnd: 5599 } },
        { id: "c5-group", label: "十人不能争抢", text: "所有人争夺一块板只会互相暴露；队列必须共享同一防线。", note: "决定权集中在前方两人。", sourceRef: { chapter: 40, lineStart: 5611, lineEnd: 5659 } },
      ],
      dialogue: [
        { id: "c05-qixia-002", speakerId: "qixia", text: "答案就是老鹰捉小鸡。", sourceRef: { chapter: 41, lineStart: 5685, lineEnd: 5685 } },
        { id: "c05-qiao-003", speakerId: "qiao", text: "母你老母啊，能不能换个名字？", sourceRef: { chapter: 41, lineStart: 5699, lineEnd: 5699 } },
      ],
      puzzle: {
        id: "c5-formation-board",
        prompt: "为铁板、观察者和其余队员分配位置。",
        requiredObservationIds: ["c5-roll", "c5-group"],
        errorCost: 1,
        solvedText: "乔家劲用肩抵住铁板；齐夏从后方拉动衣服指示左右；其余八人排成纵列随板转动。",
        fields: [
          { id: "front", label: "正面承力", correctValue: "qiao", options: [{ value: "qixia", label: "齐夏" }, { value: "qiao", label: "乔家劲" }, { value: "old-lu", label: "老吕" }], wrongMessages: { qixia: "齐夏负责观察方向，体力不足以独自承受撞击。", "old-lu": "老吕先前只想独占铁板，且无法稳定承力。" } },
          { id: "guide", label: "方向控制", correctValue: "qixia-behind", options: [{ value: "qixia-behind", label: "齐夏站后方拉衣服指向" }, { value: "qixia-front", label: "齐夏站在铁板正前" }, { value: "everyone-shouts", label: "所有人同时报方向" }], wrongMessages: { "qixia-front": "铁板前方就是黑熊攻击面。", "everyone-shouts": "多人同时指挥会让圆板失去统一方向。" } },
          { id: "others", label: "其余队员", correctValue: "single-column", options: [{ value: "scatter", label: "分散绕圈" }, { value: "corner", label: "全部挤在墙角" }, { value: "single-column", label: "纵列跟在观察者身后" }], wrongMessages: { scatter: "分散会让黑熊逐个选择目标。", corner: "铁板无法同时封住墙角的两侧。" } },
        ],
        fatalRules: [{ fieldId: "others", value: "scatter", failureId: "formation-breach", reason: "队伍分散后，圆铁板只能挡住一个方向；黑熊从侧面扑向齐夏。", checkpointSceneId: "c5-formation" }],
      },
      animationId: "c5-plate-formation",
      advanceLabel: "维持阵型",
    },
    {
      id: "c5-rescue",
      title: "趋利避害",
      eyebrow: "倒计时 03:10",
      lead: "老吕抛下队伍，黑熊转向这个孤立目标。小眼镜愿意冒死救人；齐夏先要求两人的通关奖励，再用动物弱点改变攻击目标。",
      sourceRef: { chapter: 42, lineStart: 5823, lineEnd: 5952 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["qixia", "qiao"],
      observations: [
        { id: "c5-shoes", label: "小眼镜的鞋", text: "场地没有投掷物，但小眼镜脚上有两只运动鞋。", note: "一次攻击背部，一次打向敏感鼻部。", sourceRef: { chapter: 42, lineStart: 5899, lineEnd: 5945 } },
        { id: "c5-debt", label: "救命交易", text: "小眼镜替自己和老吕担保：两人的通关奖励都交给齐夏。", note: "交易成立后才执行救援。", sourceRef: { chapter: 42, lineStart: 5873, lineEnd: 5897 } },
      ],
      dialogue: [
        { id: "c05-qixia-003", speakerId: "qixia", text: "这场游戏如果我能让你们活下来，你们俩的道归我。", sourceRef: { chapter: 42, lineStart: 5877, lineEnd: 5877 } },
      ],
      puzzle: {
        id: "c5-rescue-board",
        prompt: "用两次投掷把黑熊从老吕身边拉回铁板正面。",
        requiredObservationIds: ["c5-shoes", "c5-debt"],
        errorCost: 1,
        solvedText: "第一只鞋袭击背部，第二只鞋击中鼻子；黑熊放弃老吕，重新向铁板冲锋。",
        fields: [
          { id: "payment", label: "交易代价", correctValue: "two-rewards", options: [{ value: "free", label: "无条件救援" }, { value: "two-rewards", label: "小眼镜与老吕的两份奖励" }, { value: "all-yellow", label: "黄队全部奖励" }], wrongMessages: { free: "齐夏先明确交易，再承担引熊风险。", "all-yellow": "交易只涉及小眼镜和老吕。" } },
          { id: "first-hit", label: "第一只鞋", correctValue: "back", options: [{ value: "back", label: "黑熊背部" }, { value: "plate", label: "圆铁板" }, { value: "old-lu", label: "老吕" }], wrongMessages: { plate: "敲铁板不能稳定改变黑熊目标。", "old-lu": "攻击被救者只会让他继续孤立。" } },
          { id: "second-hit", label: "第二只鞋", correctValue: "nose", options: [{ value: "paw", label: "前掌" }, { value: "nose", label: "鼻部" }, { value: "wall", label: "墙面" }], wrongMessages: { paw: "黑熊前掌耐受冲击，无法形成足够刺激。", wall: "与黑熊无关的声响不足以覆盖眼前猎物。" } },
        ],
      },
      animationId: "c5-shoe-bait",
      advanceLabel: "迎接最后冲锋",
    },
    {
      id: "c5-final",
      title: "最后二十秒",
      eyebrow: "倒计时 00:20",
      lead: "黑熊把铁板向外拉翻。齐夏倒地，乔家劲负伤，小眼镜必须把追击从齐夏身上引开，坚持到计时归零。",
      sourceRef: { chapter: 43, lineStart: 5953, lineEnd: 6238 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["qiao", "qixia"],
      observations: [
        { id: "c5-pull", label: "黑熊改变受力", text: "黑熊不再向内压板，而是抓住边缘向外拉，借众人反向用力掀翻铁板。", note: "阵型已经失效，只剩拖延时间。", sourceRef: { chapter: 43, lineStart: 6011, lineEnd: 6033 } },
        { id: "c5-clock", label: "不足二十秒", text: "计时器接近零；铁门会在时间到达时强制回收黑熊。", note: "目标不再是重建阵型，而是让齐夏活过最后几秒。", sourceRef: { chapter: 43, lineStart: 6059, lineEnd: 6085 } },
      ],
      dialogue: [
        { id: "c05-glasses-001", speakerId: "little-glasses", text: "喂！王八蛋！别动他！", sourceRef: { chapter: 43, lineStart: 6075, lineEnd: 6075 } },
        { id: "c05-qiao-004", speakerId: "qiao", text: "时间到了！别再杀人了！", sourceRef: { chapter: 44, lineStart: 6115, lineEnd: 6115 } },
      ],
      puzzle: {
        id: "c5-final-sequence",
        prompt: "排列最后二十秒的三次动作。",
        requiredObservationIds: ["c5-pull", "c5-clock"],
        errorCost: 1,
        solvedText: "乔家劲顶膝打断扑杀，小眼镜主动嘲讽引走黑熊，倒计时归零后铁门将黑熊吸回。",
        fields: [
          { id: "first", label: "第一步", correctValue: "qiao-knee", options: [{ value: "rebuild", label: "重新抬起铁板" }, { value: "qiao-knee", label: "乔家劲侧面顶膝" }, { value: "qixia-run", label: "齐夏立刻冲刺" }], wrongMessages: { rebuild: "铁板压在地上，二十秒内来不及恢复完整阵型。", "qixia-run": "齐夏胸口撞伤，反复起身失败。" } },
          { id: "second", label: "第二步", correctValue: "glasses-taunt", options: [{ value: "glasses-taunt", label: "小眼镜出声引走黑熊" }, { value: "everyone-silent", label: "所有人保持安静" }, { value: "old-lu-bait", label: "再次推出老吕" }], wrongMessages: { "everyone-silent": "黑熊当前目标就是倒地的齐夏。", "old-lu-bait": "原著中主动站出来的是小眼镜。" } },
          { id: "third", label: "第三步", correctValue: "call-zero", options: [{ value: "fight-bear", label: "徒手杀死黑熊" }, { value: "call-zero", label: "盯住计时器并叫停" }, { value: "open-gate", label: "手动抬起铁门" }], wrongMessages: { "fight-bear": "黄队没有张山，目标是坚持到十分钟。", "open-gate": "铁门只能由场外机制开启。" } },
        ],
        fatalRules: [{ fieldId: "second", value: "everyone-silent", failureId: "last-seconds", reason: "没有新的目标打断扑杀，黑熊在计时归零前抓住了倒地的齐夏。", checkpointSceneId: "c5-final" }],
      },
      animationId: "c5-final-twenty",
      advanceLabel: "返回分队房",
    },
    {
      id: "c5-settlement",
      title: "十九名通关者",
      eyebrow: "地牛结算",
      lead: "黄队九人生还，绿队十人生还。张山用铁板打死另一只黑熊并带回两条熊臂。",
      sourceRef: { chapter: 44, lineStart: 6087, lineEnd: 6482 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["ground-ox", "zhang-shan", "qixia"],
      observations: [
        { id: "c5-nineteen", label: "十九人", text: "两队合计十九人通关，因此每名幸存者获得十九颗“道”。", note: "四人份为七十六颗。", sourceRef: { chapter: 45, lineStart: 6239, lineEnd: 6249 } },
        { id: "c5-zhang", label: "张山的熊臂", text: "张山以铁板压住黑熊并持续攻击，绿队十人无一死亡。", note: "他的正面力量足以改变后续格局。", sourceRef: { chapter: 45, lineStart: 6261, lineEnd: 6299 } },
      ],
      dialogue: [
        { id: "c05-ox-002", speakerId: "ground-ox", text: "每人十九颗道，游戏结束。", sourceRef: { chapter: 45, lineStart: 6241, lineEnd: 6241 } },
        { id: "c05-zhang-001", speakerId: "zhang-shan", text: "干……老牛，你还真是不客气，熊这种东西都准备好了？", sourceRef: { chapter: 44, lineStart: 6229, lineEnd: 6229 } },
      ],
      canonicalEvent: "队伍四人得到七十六颗，齐夏依据交易取得小眼镜与老吕的三十八颗，再归还小眼镜一袋十九颗；连同赛前剩余一颗，净持有九十六颗。",
      daoDeltaOnAdvance: 95,
      animationId: "c5-dao-settlement",
      advanceLabel: "处理张山的来意",
    },
    {
      id: "c5-confrontation",
      title: "大脑与拳头",
      eyebrow: "结算后 / 椅阵",
      lead: "齐夏误判张山来意，先用椅子攻击。乔家劲接替他与张山交手，地牛最终将两人分开。",
      sourceRef: { chapter: 46, lineStart: 6483, lineEnd: 6618 },
      backgroundAsset: "/art/chapter-05/underground-arena-v1.png",
      portraitIds: ["qixia", "qiao", "zhang-shan"],
      observations: [
        { id: "c5-chair", label: "椅子与伤势", text: "张山刚经历熊战、胸前有伤；齐夏利用椅子制造距离并抢先攻击。", note: "这不是公平格斗，而是先手求生。", sourceRef: { chapter: 45, lineStart: 6325, lineEnd: 6401 } },
        { id: "c5-brain-fist", label: "大脑与拳头", text: "乔家劲称齐夏为自己的“大脑”，自己则是他的“拳头”。", note: "两人的合作关系第一次被明确命名。", sourceRef: { chapter: 46, lineStart: 6539, lineEnd: 6551 } },
      ],
      dialogue: [
        { id: "c05-qiao-005", speakerId: "qiao", text: "他是我的大脑。你打坏他的头，我俩可就都变傻了。", sourceRef: { chapter: 46, lineStart: 6543, lineEnd: 6543 } },
        { id: "c05-qiao-006", speakerId: "qiao", text: "如果非要说的话，我是他的拳头。", sourceRef: { chapter: 46, lineStart: 6549, lineEnd: 6549 } },
      ],
      puzzle: {
        id: "c5-conflict-board",
        prompt: "按正史固定这场冲突中的角色职责。",
        requiredObservationIds: ["c5-chair", "c5-brain-fist"],
        errorCost: 1,
        solvedText: "齐夏负责抢先制造战术距离；乔家劲接管正面对抗；地牛凭绝对力量终止缠斗。",
        fields: [
          { id: "qixia-role", label: "齐夏", correctValue: "chair-ambush", options: [{ value: "fair-boxing", label: "提出公平拳赛" }, { value: "chair-ambush", label: "利用椅子与伤势抢先" }, { value: "hide", label: "躲到甜甜身后" }], wrongMessages: { "fair-boxing": "齐夏不是格斗家，他使用环境和先手。", hide: "齐夏主动攻击张山。" } },
          { id: "qiao-role", label: "乔家劲", correctValue: "front-fighter", options: [{ value: "front-fighter", label: "接管正面对抗" }, { value: "leave", label: "离开场地" }, { value: "help-zhang", label: "帮助张山" }], wrongMessages: { leave: "乔家劲明确保护自己的“大脑”。", "help-zhang": "他与张山进行十字固和裸绞对抗。" } },
          { id: "stopper", label: "终止冲突", correctValue: "ground-ox", options: [{ value: "ground-ox", label: "地牛" }, { value: "little-glasses", label: "小眼镜" }, { value: "tiantian", label: "甜甜" }], wrongMessages: { "little-glasses": "小眼镜劝架失败。", tiantian: "甜甜只在事后扶起乔家劲。" } },
        ],
      },
      animationId: "c5-brain-fist",
      advanceLabel: "听完逃离者笔记",
    },
    {
      id: "c5-harvest",
      title: "逃离的可能",
      eyebrow: "离开地牛场地",
      lead: "张山说他们找到过一名逃离者的笔记，并留下血画地图。齐夏拒绝加入，也拒绝让独自存活的微胖女子靠近队伍。",
      sourceRef: { chapter: 47, lineStart: 6619, lineEnd: 6744 },
      backgroundAsset: "/art/chapter-02/termination-city-v1.png",
      portraitIds: ["zhang-shan", "qixia", "qiao"],
      observations: [
        { id: "c5-escape-note", label: "逃离者笔记", text: "张山没有见过逃离者本人，只找到一份笔记，并以此相信多人可以一起离开。", note: "“只有一人能出去”从未被生肖明确说过。", sourceRef: { chapter: 47, lineStart: 6671, lineEnd: 6699 } },
        { id: "c5-woman", label: "独活的弱女子", text: "她声称八名队友全死在面试中，自己却独自存活至今并主动接近大量“道”。", note: "齐夏只记录高风险，不宣称已经证明她的身份。", sourceRef: { chapter: 48, lineStart: 6721, lineEnd: 6743 } },
      ],
      dialogue: [
        { id: "c05-zhang-002", speakerId: "zhang-shan", text: "我们正在聚集一批厉害的人物，然后一起走出这个地方。", sourceRef: { chapter: 47, lineStart: 6655, lineEnd: 6655 } },
        { id: "c05-qixia-004", speakerId: "qixia", text: "我是个骗子。我的话不要信。", sourceRef: { chapter: 48, lineStart: 6689, lineEnd: 6689 } },
      ],
      advanceLabel: "带着收获离开",
    },
  ],
};

export const STORY_CHAPTERS: Record<StoryChapterId, StoryChapterSpec> = {
  3: chapterThree,
  4: chapterFour,
  5: chapterFive,
};

export function storyChapterSpec(chapterId: StoryChapterId) {
  return STORY_CHAPTERS[chapterId];
}
